// B2.5 manual compatibility fail-closed and canonical parity gates.
import { randomUUID } from "node:crypto";
import { neon } from "@neondatabase/serverless";
const q=neon(process.env.DATABASE_URL); const core=await import("./src/data/battery-compat-core.ts"); const {ensureSchema}=await import("./src/data/migrations.ts"); await ensureSchema();
const org=`qa-b25-${randomUUID()}`, owner=`qa-b25-owner-${randomUUID()}`; const checks=[]; const check=(n,v)=>{checks.push([n,!!v]);if(!v)throw Error(`FAIL: ${n}`)};
const clean=async()=>{for(const t of ["battery_compatibility","battery_products"])await q.unsafe(`DELETE FROM ${t} WHERE org_id=$1`,[org]);await q`DELETE FROM organization_memberships WHERE org_id=${org}`;await q`DELETE FROM users WHERE id=${owner}`;await q`DELETE FROM organizations WHERE id=${org}`};
const add=async({trim=null,engine=null,group="47"}={})=>q`INSERT INTO battery_compatibility(id,org_id,make,model,year_from,year_to,trim,engine,battery_group_size,status,source_reference_internal) VALUES(gen_random_uuid()::text,${org},'FORD','F-150',2020,2025,${trim},${engine},${group},'approved','qa-b25')`;
try{await clean();await q`INSERT INTO organizations(id,name) VALUES(${org},'QA B2.5')`;await q`INSERT INTO users(id,name,email,password_hash) VALUES(${owner},'QA',${owner+'@qa.local'},'x')`;await q`INSERT INTO organization_memberships(org_id,user_id,role) VALUES(${org},${owner},'owner')`;await q`INSERT INTO battery_products(id,org_id,group_size,display_name,retail_cents,installation_cents,warranty_years,free_replacement_years,core_charge_cents,availability,active) VALUES(gen_random_uuid()::text,${org},'47','LIGHTNING GOLD BATTERY',20000,0,3,3,0,'in_stock',true)`;const u={orgId:org,role:'owner',id:owner};
await add();
let r=await core.lookupBatteryCompatibilityCore(u,{make:'ford',model:'f-150',year:'2022'});check('exact generic match',r.ok&&r.outcome==='matched'&&r.match.batteryGroupSize==='47');
r=await core.lookupBatteryCompatibilityCore(u,{make:'ford',model:'unknown',year:'2022'});check('no match review',r.ok&&r.outcome==='review'&&r.reason==='not_found');
await add({trim:'XL'});r=await core.lookupBatteryCompatibilityCore(u,{make:'ford',model:'f-150',year:2022,trim:'XL'});check('generic plus specific ambiguity',r.ok&&r.outcome==='review'&&r.reason==='ambiguous');
await clean();await q`INSERT INTO organizations(id,name) VALUES(${org},'QA B2.5')`;await q`INSERT INTO users(id,name,email,password_hash) VALUES(${owner},'QA',${owner+'@qa.local'},'x')`;await q`INSERT INTO organization_memberships(org_id,user_id,role) VALUES(${org},${owner},'owner')`;await q`INSERT INTO battery_products(id,org_id,group_size,display_name,retail_cents,installation_cents,warranty_years,free_replacement_years,core_charge_cents,availability,active) VALUES(gen_random_uuid()::text,${org},'47','LIGHTNING GOLD BATTERY',20000,0,3,3,0,'in_stock',true)`;
r=await core.lookupBatteryCompatibilityCore(u,{make:'ford',model:'f-150',year:2022,trim:'XL'});check('empty table review',r.ok&&r.outcome==='review');await add({trim:'XL'});r=await core.lookupBatteryCompatibilityCore(u,{make:'ford',model:'f-150',year:2022});check('specific requires field',r.ok&&r.outcome==='review');r=await core.lookupBatteryCompatibilityCore(u,{make:'ford',model:'f-150',year:2022,trim:'XL'});check('specific exact match',r.ok&&r.outcome==='matched');
const fetchImpl=async()=>new Response(JSON.stringify({Results:[{Make:'FORD',Model:'F-150',ModelYear:'2022',Trim:'XL',EngineModel:''}]}),{status:200});const vin=await core.lookupBatteryCompatibilityFromVinCore(u,{vin:'1HGCM82633A004352'},fetchImpl);check('manual equals VIN result',JSON.stringify(vin)===JSON.stringify(r));const dto=vin.ok&&vin.outcome==='matched'?vin.match:null;check('exact serializer keys',dto&&JSON.stringify(Object.keys(dto).sort())===JSON.stringify(['batteryGroupSize','compatibilityId','displayBatteryGroup','make','model','year'].sort()));console.log(`PASS B2.5 (${checks.filter(x=>x[1]).length}/${checks.length} checks)`)}finally{await clean()}
