import { strict as assert } from "node:assert";
import { calculateInternalEta, normalizeEtaServiceType, serviceMinutesFor, routeKey, normalizeBatteryInstallType, serializeEtaForAudience } from "./src/lib/internal-eta.ts";
const p = (lat) => ({ lat, lng: -73 });
const job = (id, status = "accepted", type = "jump start", lat = 1) => ({ id, status, serviceType: type, location: p(lat) });
const routes = (pairs) => Object.fromEntries(pairs.map(([a, b, seconds, distanceMeters]) => [routeKey(a, b), { durationSeconds: seconds, distanceMeters }]));
const base = { liveLocation: p(0), jobs: [], routes: {} };
assert.equal(calculateInternalEta(base).ok, true);
let one = calculateInternalEta({ ...base, jobs: [job("a")], routes: routes([["live", "a", 600, 1000]]) });
assert.deepEqual(one.orderedJobIds, ["a"]); assert.equal(one.breakdown[0].arrivalOffsetMinutes, 10); assert.equal(one.totalMinutes, 15 / 1);
assert.equal(serviceMinutesFor({ serviceType: "mystery" }).unknown, true);
assert.equal(serviceMinutesFor({ serviceType: "battery installation", batteryInstallType: "advanced" }).minutes, 120);
assert.equal(normalizeEtaServiceType("door unlock"), "lockout");
assert.equal(normalizeBatteryInstallType("EUROPEAN").minutes, 15); assert.equal(normalizeBatteryInstallType("EUROPEAN").reviewRequired, true);
assert.equal(normalizeBatteryInstallType("bogus").minutes, 15);
assert.deepEqual(serializeEtaForAudience(one, "customer"), { ok: true, etaMinutes: 15 });
assert.equal("breakdown" in serializeEtaForAudience(one, "customer"), false);
const numeric = calculateInternalEta({ ...base, jobs: [job("numeric", 70)], routes: routes([["live", "numeric", 60]]) }); assert.deepEqual(numeric.orderedJobIds, ["numeric"]);
const unknown = calculateInternalEta({ ...base, jobs: [job("unknown", "accepted", "unmapped")], routes: routes([["live", "unknown", 60]]) }); assert.equal(unknown.reviewRequired, true);
assert.equal(calculateInternalEta({ ...base, liveLocation: null }).reason, "missing_live_location");
const inactive = calculateInternalEta({ ...base, jobs: [job("x", "completed")], routes: {} }); assert.deepEqual(inactive.orderedJobIds, []);
const three = [job("bridgeport", "accepted", "jump", 1), job("fairfield", "accepted", "tire", 2), job("trumbull", "accepted", "fuel", 3)];
const matrix = routes([["live", "bridgeport", 100], ["live", "fairfield", 10], ["live", "trumbull", 30], ["bridgeport", "fairfield", 10], ["bridgeport", "trumbull", 20], ["fairfield", "bridgeport", 10], ["fairfield", "trumbull", 10], ["trumbull", "bridgeport", 10], ["trumbull", "fairfield", 10]]);
const inserted = calculateInternalEta({ ...base, jobs: three, routes: matrix }); assert.deepEqual(inserted.orderedJobIds, ["fairfield", "trumbull", "bridgeport"]);
const committed = calculateInternalEta({ ...base, jobs: [job("started", "in_progress"), job("later", "accepted")], routes: routes([["live", "started", 10], ["started", "later", 100], ["live", "later", 1], ["later", "started", 1]]) }); assert.deepEqual(committed.orderedJobIds, ["started", "later"]);
const changed = calculateInternalEta({ ...base, jobs: [job("a")], routes: routes([["live", "a", 60]]) }); assert.equal(changed.breakdown[0].travelMinutes, 1);
const preview = calculateInternalEta({ ...base, jobs: [job("a")], offer: job("offer", "offered", "fuel", 2), routes: routes([["live", "a", 60], ["a", "offer", 120]]) }); assert.deepEqual(preview.orderedJobIds, ["a"]); assert.equal(preview.preview, true); assert.equal(preview.breakdown.at(-1).jobId, "offer");
console.log("internal ETA hermetic tests: PASS");
import { createEtaRecalculationHooks, trafficRefreshNeeded, recalculateInternalEta } from "./src/lib/internal-eta-orchestration.ts";
const triggerLog = [];
const hooks = createEtaRecalculationHooks(async (trigger, key) => { triggerLog.push([key, trigger]); return { key, trigger }; }, () => 123);
assert.deepEqual(await hooks.onOfferAssignment("offer-1"), { trigger: "offer_assignment", key: "offer-1", value: { key: "offer-1", trigger: "offer_assignment" }, recalculatedAt: 123 });
assert.deepEqual(await hooks.onStatusChange("job-1").then(x => x.trigger), "status_change");
assert.deepEqual(await hooks.onFreshGps("driver-1").then(x => x.trigger), "fresh_gps");
assert.deepEqual(await hooks.onTrafficRefresh("org-1").then(x => x.trigger), "traffic_refresh");
assert.equal(triggerLog.length, 4);
assert.equal(trafficRefreshNeeded(null, 100, 60), true); assert.equal(trafficRefreshNeeded(50, 100, 60), false); assert.equal(trafficRefreshNeeded(40, 100, 60), true);
assert.deepEqual(await recalculateInternalEta({ trigger: "traffic_refresh", key: "org-1", calculate: async () => ({ secret: true }), now: () => 456 }), { trigger: "traffic_refresh", key: "org-1", value: { secret: true }, recalculatedAt: 456 });
console.log("internal ETA orchestration hooks: PASS");
const customerSafe = serializeEtaForAudience(one, "customer");
assert.equal(Object.prototype.hasOwnProperty.call(customerSafe, "breakdown"), false);
assert.equal(Object.keys(customerSafe).some((key) => /travel|service|sequence|review/i.test(key)), false);
