import { strict as assert } from "node:assert";
import { calculateInternalEta, normalizeEtaServiceType, serviceMinutesFor, routeKey } from "./src/lib/internal-eta.ts";
const p = (lat) => ({ lat, lng: -73 });
const job = (id, status = "accepted", type = "jump start", lat = 1) => ({ id, status, serviceType: type, location: p(lat) });
const routes = (pairs) => Object.fromEntries(pairs.map(([a, b, seconds, distanceMeters]) => [routeKey(a, b), { durationSeconds: seconds, distanceMeters }]));
const base = { liveLocation: p(0), jobs: [], routes: {} };
assert.equal(calculateInternalEta(base).ok, true);
let one = calculateInternalEta({ ...base, jobs: [job("a")], routes: routes([["live", "a", 600, 1000]]) });
assert.deepEqual(one.orderedJobIds, ["a"]); assert.equal(one.breakdown[0].arrivalOffsetMinutes, 10); assert.equal(one.totalMinutes, 15 / 1);
assert.equal(serviceMinutesFor({ serviceType: "mystery" }).unknown, true);
assert.equal(serviceMinutesFor({ serviceType: "battery installation", batteryInstallType: "advanced" }).minutes, 120);
assert.equal(normalizeEtaServiceType("door unlock"), "lockout");
assert.equal(calculateInternalEta({ ...base, liveLocation: null }).reason, "missing_live_location");
const inactive = calculateInternalEta({ ...base, jobs: [job("x", "completed")], routes: {} }); assert.deepEqual(inactive.orderedJobIds, []);
const three = [job("bridgeport", "accepted", "jump", 1), job("fairfield", "accepted", "tire", 2), job("trumbull", "accepted", "fuel", 3)];
const matrix = routes([["live", "bridgeport", 100], ["live", "fairfield", 10], ["live", "trumbull", 30], ["bridgeport", "fairfield", 10], ["bridgeport", "trumbull", 20], ["fairfield", "bridgeport", 10], ["fairfield", "trumbull", 10], ["trumbull", "bridgeport", 10], ["trumbull", "fairfield", 10]]);
const inserted = calculateInternalEta({ ...base, jobs: three, routes: matrix }); assert.deepEqual(inserted.orderedJobIds, ["fairfield", "trumbull", "bridgeport"]);
const committed = calculateInternalEta({ ...base, jobs: [job("started", "in_progress"), job("later", "accepted")], routes: routes([["live", "started", 10], ["started", "later", 100], ["live", "later", 1], ["later", "started", 1]]) }); assert.deepEqual(committed.orderedJobIds, ["started", "later"]);
const changed = calculateInternalEta({ ...base, jobs: [job("a")], routes: routes([["live", "a", 60]]) }); assert.equal(changed.breakdown[0].travelMinutes, 1);
const preview = calculateInternalEta({ ...base, jobs: [job("a")], offer: job("offer", "offered", "fuel", 2), routes: routes([["live", "a", 60], ["a", "offer", 120]]) }); assert.deepEqual(preview.orderedJobIds, ["a"]); assert.equal(preview.preview, true); assert.equal(preview.breakdown.at(-1).jobId, "offer");
console.log("internal ETA hermetic tests: PASS");
