import assert from "node:assert/strict";
import { checkReservedZoneEligibility } from "./src/data/reserved-zone-core.ts";
const zone=(x={})=>({id:"z",is_reserved:true,unlock_jobs_required:3,...x});
assert.equal(checkReservedZoneEligibility({zone:zone(),completedJobs:3}).ok,true);
assert.equal(checkReservedZoneEligibility({zone:zone(),completedJobs:2}).ok,false);
assert.equal(checkReservedZoneEligibility({zone:zone(),completedJobs:0}).ok,false);
assert.equal(checkReservedZoneEligibility({zone:zone({unlock_jobs_required:0}),completedJobs:0}).ok,true);
assert.equal(checkReservedZoneEligibility({zone:zone({is_reserved:false}),completedJobs:0}).ok,true);
assert.equal(checkReservedZoneEligibility({zone:null,completedJobs:3}).ok,false);
assert.equal(checkReservedZoneEligibility({zone:zone(),completedJobs:3,actorRole:"contractor",explicitOwnerOverride:true}).ok,true);
assert.equal(checkReservedZoneEligibility({zone:zone(),completedJobs:0,actorRole:"owner",explicitOwnerOverride:true}).ok,true);
assert.equal(checkReservedZoneEligibility({zone:zone(),completedJobs:0,actorRole:"admin",explicitOwnerOverride:true}).ok,true);
assert.equal(checkReservedZoneEligibility({zone:zone(),completedJobs:0,actorRole:"manager",explicitOwnerOverride:true}).ok,false);
assert.equal(checkReservedZoneEligibility({zone:zone({unlock_jobs_required:null}),completedJobs:99}).ok,false);
console.log("ok - reserved-zone eligibility boundary, fail-closed, non-reserved, and override tests");
