import { createFileRoute, useNavigate, useSearch } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { Button, Card } from "~/components/ui";
import { authStatus, createOwner, login } from "~/data/auth";
export const Route = createFileRoute('/login')({ component: Login });
function Login(){ const nav=useNavigate(); const search=useSearch({from:"/login" as any}) as {next?:string}; const [first,setFirst]=useState(false); const [name,setName]=useState(""); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
 useEffect(()=>{void authStatus().then((s)=>{if(s.mode!=="demo" && s.user) void nav({to:s.user.role==="contractor"?"/driver":s.user.role==="dispatcher"?"/ops":"/owner",replace:true}); else if(s.mode!=="demo") setFirst(!!s.needsOwner);}).catch(()=>{ /* keep login available when auth check fails */ });},[nav]);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError(""); try { const r=first?await createOwner({data:{name,email,password}}):await login({data:{email,password}}); if(!r.ok){setError(r.error);return;} void nav({to:search.next||(first?"/owner": "/owner"),replace:true}); } catch (err) { setError(err instanceof Error ? err.message : "Unable to sign in. Please try again."); } finally { setBusy(false); }}
 return <main className="grid min-h-dvh place-items-center bg-canvas px-4"><Card className="w-full max-w-md p-7"><div className="mb-7"><p className="text-xs font-bold uppercase tracking-[.18em] text-brand-600">Lightning Dispatch OS</p><h1 className="mt-2 text-2xl font-bold text-ink-800">{first?"Create owner account":"Welcome back"}</h1><p className="mt-2 text-sm text-ink-400">{first?"Set the owner credentials for your organization.":"Sign in to your operations workspace."}</p></div><form onSubmit={submit} className="space-y-4">{first&&<label className="block text-sm font-semibold text-ink-700">Name<input required value={name} onChange={e=>setName(e.target.value)} className="mt-1 h-11 w-full rounded-xl border border-ink-200 px-3" /></label>}<label className="block text-sm font-semibold text-ink-700">Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="mt-1 h-11 w-full rounded-xl border border-ink-200 px-3" /></label><label className="block text-sm font-semibold text-ink-700">Password<input required type="password" minLength={10} value={password} onChange={e=>setPassword(e.target.value)} className="mt-1 h-11 w-full rounded-xl border border-ink-200 px-3" /><span className="mt-1 block text-xs font-normal text-ink-400">At least 10 characters</span></label>{error&&<p role="alert" className="rounded-xl bg-danger-50 p-3 text-sm text-danger-600">{error}</p>}<Button type="submit" loading={busy} className="w-full">{first?"Create owner account":"Sign in"}</Button></form></Card></main> }
