import { useEffect, useMemo, useState } from "react";
import { Check, Loader2, Save, Wrench } from "lucide-react";
import { Card, Button } from "~/components/ui";
import { getMyServices, setMyServices, listContractorServices, setContractorServices, bulkSetContractorServices, type ServiceSelectionRow } from "~/data/service-selection";

const OPTIONS = [
  ["jump_start", "Jump start"], ["tire_change", "Tire change"], ["fuel_delivery", "Fuel delivery"],
  ["lockout", "Unlock / lockout"], ["battery_standard", "Battery — standard"], ["battery_advanced", "Battery — advanced"], ["heavy_tow", "Heavy tow"],
] as const;
function ServiceChecks({ value, onChange, disabled = false }: { value: string[]; onChange: (v: string[]) => void; disabled?: boolean }) {
  return <div className="grid gap-2 sm:grid-cols-2">{OPTIONS.map(([key, label]) => { const checked = value.includes(key); return <label key={key} className={`flex min-h-12 cursor-pointer items-center gap-3 rounded-xl border px-3 py-2 text-sm ${checked ? "border-brand-300 bg-brand-50 text-brand-800" : "border-ink-100 bg-surface text-ink-600"} ${disabled ? "cursor-not-allowed opacity-60" : ""}`}><input type="checkbox" checked={checked} disabled={disabled} onChange={() => onChange(checked ? value.filter((x) => x !== key) : [...value, key])} className="size-4 accent-brand-600" /><span className="font-semibold">{label}</span>{checked && <Check className="ml-auto size-4 text-brand-600" />}</label>; })}</div>;
}
export function DriverServiceSelection() {
  const [services, setServices] = useState<string[] | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  useEffect(() => { void getMyServices().then((r) => { if (r.ok) setServices(r.data.services.selectedServices); else setError(r.message); }).catch(() => setError("Unable to load your services.")); }, []);
  const save = async () => { if (!services) return; setBusy(true); setMessage(""); setError(""); const r = await setMyServices({ data: { services } }); setBusy(false); if (r.ok) { setServices(r.data.selectedServices); setMessage(r.data.selectedServices.length ? "Services saved. Dispatch will use this list." : "Saved with no services. You will not receive dispatches until you select a service."); } else setError(r.message); };
  return <Card className="p-5"><div className="flex items-start gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-brand-50 text-brand-600"><Wrench className="size-5" /></span><div><h2 className="text-base font-bold">Services you provide</h2><p className="mt-1 text-sm leading-relaxed text-ink-500">Choose the work you are equipped and willing to accept. Your list is used for dispatch qualification.</p></div></div>{services === null ? <div className="grid place-items-center p-8"><Loader2 className="size-5 animate-spin text-brand-500" /></div> : <><div className="mt-5"><ServiceChecks value={services} onChange={setServices} disabled={busy} /></div><div className="mt-4 flex flex-wrap items-center gap-3"><Button loading={busy} onClick={() => void save()}><Save className="size-4" /> Save services</Button>{message && <p className="text-sm font-semibold text-success-700">{message}</p>}{error && <p className="text-sm font-semibold text-danger-600">{error}</p>}</div></>}</Card>;
}
export function OwnerServiceSelection({ contractorId }: { contractorId?: string }) {
  const [rows, setRows] = useState<ServiceSelectionRow[] | null>(null); const [selected, setSelected] = useState<string[]>([]); const [bulk, setBulk] = useState<string[]>([]); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const load = async () => { const r = await listContractorServices(); if (r.ok) { setRows(r.data); if (contractorId) setSelected(r.data.find((x) => x.contractorId === contractorId)?.selectedServices ?? []); } else setError(r.message); };
  useEffect(() => { void load(); }, [contractorId]);
  const selectedRows = useMemo(() => (rows ?? []).filter((r) => selected.includes(r.contractorId)), [rows, selected]);
  const saveOne = async () => { if (!contractorId) return; setBusy(true); setMessage(""); const r = await setContractorServices({ data: { contractorId, services: selected } }); setBusy(false); if (r.ok) { setRows((rs) => rs?.map((x) => x.contractorId === contractorId ? r.data : x) ?? rs); setMessage("Services updated for this contractor."); } else setError(r.message); };
  const saveBulk = async () => { if (!selected.length) return; setBusy(true); setMessage(""); const r = await bulkSetContractorServices({ data: { contractorIds: selected, services: bulk } }); setBusy(false); if (r.ok) { setMessage(`Updated ${r.data.updated} contractors.`); await load(); } else setError(r.message); };
  if (!rows) return <Card className="grid place-items-center p-8"><Loader2 className="size-5 animate-spin text-brand-500" /></Card>;
  if (contractorId) return <Card className="p-5"><h2 className="text-base font-bold">Services for this contractor</h2><p className="mt-1 text-sm text-ink-500">Owner edits are authoritative and match the contractor app.</p><div className="mt-4"><ServiceChecks value={selected} onChange={setSelected} disabled={busy} /></div><div className="mt-4 flex flex-wrap items-center gap-3"><Button loading={busy} onClick={() => void saveOne()}>Save services</Button>{message && <span className="text-sm font-semibold text-success-700">{message}</span>}{error && <span className="text-sm font-semibold text-danger-600">{error}</span>}</div></Card>;
  return <Card className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-base font-bold">Contractor services</h2><p className="mt-1 text-sm text-ink-500">Select contractors to edit the same capability list they see.</p></div><span className="text-xs font-bold text-ink-400">{selectedRows.length} selected</span></div><div className="mt-4 space-y-2">{rows.map((r) => <label key={r.contractorId} className="flex items-center gap-3 rounded-xl border border-ink-100 p-3"><input type="checkbox" checked={selected.includes(r.contractorId)} onChange={() => setSelected((xs) => xs.includes(r.contractorId) ? xs.filter((x) => x !== r.contractorId) : [...xs, r.contractorId])} className="size-4 accent-brand-600" /><span className="min-w-0 flex-1"><span className="block truncate text-sm font-bold">{r.contractorName}</span><span className="block text-xs text-ink-400">{r.selectedServices.length ? r.selectedServices.map((x) => OPTIONS.find(([k]) => k === x)?.[1] ?? x).join(" · ") : "No services selected — fail-closed"}</span></span></label>)}</div>{selected.length > 0 && <><p className="mt-5 text-sm font-bold">Bulk replacement for selected contractors</p><div className="mt-2"><ServiceChecks value={bulk} onChange={setBulk} disabled={busy} /></div><div className="mt-4 flex flex-wrap items-center gap-3"><Button loading={busy} onClick={() => void saveBulk()}><Save className="size-4" /> Apply to {selected.length}</Button>{message && <span className="text-sm font-semibold text-success-700">{message}</span>}{error && <span className="text-sm font-semibold text-danger-600">{error}</span>}</div></>}</Card>;
}
