/** Customer-present tire-plug opt-in, mounted on tire-change driver jobs. */
import { useEffect, useRef, useState } from "react";
import { Check, CreditCard, Sparkles } from "lucide-react";
import { Button } from "~/components/ui";
import { getSquareWebPaymentsConfig } from "~/data/completion";
import { approveTirePlug, chargeTirePlug, declineTirePlug, offerTirePlug } from "~/data/tire-plug";

type Card = { tokenize: () => Promise<{ status:string; token?:string; errors?:Array<{detail?:string}> }>; attach:(s:string)=>Promise<void>; destroy:()=>Promise<void> };
let script: Promise<void>|null=null;
const loadSquare=()=>{ if(typeof window==='undefined') return Promise.reject(new Error('Client only')); if((window as any).Square)return Promise.resolve(); return script??=new Promise((res,rej)=>{const e=document.createElement('script');e.src='https://web.squarecdn.com/v1/square.js';e.onload=()=>res();e.onerror=()=>{script=null;rej(new Error('Payment form could not load.'))};document.head.appendChild(e)}); };
const dollars=(c:number)=>`$${(c/100).toFixed(2)}`;
export function TirePlugOffer({jobId}:{jobId:string}) {
 const [row,setRow]=useState<any>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [pay,setPay]=useState(false);
 const offer=async()=>{setBusy(true);setError('');const r=await offerTirePlug({data:{jobId}});if(r.ok)setRow(r.row);else setError(r.message);setBusy(false)};
 if(!row)return <div className="mt-3 rounded-2xl border border-accent-200 bg-accent-50 p-3"><div className="flex items-center gap-2"><Sparkles className="size-4 text-accent-700"/><p className="text-sm font-bold text-ink-800">Offer an optional tire plug</p></div><p className="mt-1 text-xs text-ink-600">Tire plug service — customer chooses whether to add it.</p>{error&&<p role="alert" className="mt-2 text-xs text-danger-600">{error}</p>}<Button className="mt-3 w-full" loading={busy} onClick={offer}>Offer tire plug — $45</Button></div>;
 if(row.status==='paid')return <div className="mt-3 rounded-xl border border-success-200 bg-success-50 p-3 text-sm font-bold text-success-700"><Check className="mr-1 inline size-4"/>Tire plug paid — {dollars(row.amountCents)}</div>;
 if(row.status==='declined')return <p className="mt-3 rounded-xl bg-ink-50 p-3 text-xs font-semibold text-ink-600">Customer declined the optional tire plug. You can complete the job.</p>;
 const approve=async()=>{setBusy(true);const r=await approveTirePlug({data:{transactionId:row.id}});if(r.ok){setRow(r.row);setPay(true)}else setError(r.message);setBusy(false)};
 return <div className="mt-3 rounded-2xl border border-brand-200 bg-surface p-3"><p className="text-sm font-bold text-ink-800">Tire plug — {dollars(row.amountCents)}</p><p className="mt-1 text-xs text-ink-500">Customer approval is required. This service is optional.</p>{error&&<p role="alert" className="mt-2 text-xs text-danger-600">{error}</p>}{pay?<TirePayment row={row} onDone={setRow} onError={setError}/>:<div className="mt-3 flex gap-2"><Button className="flex-1" loading={busy} onClick={approve}>Customer opts in</Button><Button className="flex-1" variant="secondary" loading={busy} onClick={async()=>{setBusy(true);const r=await declineTirePlug({data:{transactionId:row.id}});if(r.ok)setRow(r.row);setBusy(false)}}>No thanks</Button></div>}</div>;
}
function TirePayment({row,onDone,onError}:{row:any;onDone:(r:any)=>void;onError:(s:string)=>void}){const [card,setCard]=useState<Card|null>(null);const [busy,setBusy]=useState(false);const id=useRef(`tire-${Math.random().toString(36).slice(2)}`);useEffect(()=>{let dead=false;let c:Card|null=null;(async()=>{try{const cfg=await getSquareWebPaymentsConfig();if(!cfg.ok)throw new Error(cfg.message);await loadSquare();const p=(window as any).Square.payments(cfg.applicationId,cfg.locationId);const created=await p.card();c=created;await created.attach('#'+id.current);if(!dead)setCard(created)}catch(e){if(!dead)onError(e instanceof Error?e.message:'Payment form unavailable')}})();return()=>{dead=true;if(c)void c.destroy()};},[]);return <div className="mt-3 space-y-2"><p className="rounded-lg bg-brand-50 p-2 text-xs font-semibold text-brand-700">Hand your phone to the customer to pay securely.</p><div id={id.current} className="min-h-20"/><Button className="w-full" loading={busy} disabled={!card} onClick={async()=>{if(!card)return;setBusy(true);const t=await card.tokenize();if(t.status!=='OK'||!t.token){onError(t.errors?.[0]?.detail??'Card details could not be read.');setBusy(false);return}const r=await chargeTirePlug({data:{transactionId:row.id,token:t.token,attempt:1}});if(r.ok)onDone(r.row??{...row,status:'paid'});else onError(r.message);setBusy(false)}}><CreditCard className="size-4"/> Charge {dollars(row.amountCents)}</Button></div>}
