import { useEffect, useRef, useState, type ReactNode } from 'react';
import { demandLevelToColor } from '~/lib/zone-model';
import { zoneCirclePolygon } from '~/lib/zone-circle';
import '@tomtom-international/web-sdk-maps/dist/maps.css';
export type ZoneMapItem={id:string;name:string;state:string;market:string;geometry:any;lat:number;lng:number;radiusMiles:number;demandLevel:number|null;demandSource:'set'|'computed'|'unavailable';status:'available'|'busy'|'reserved'|'at_capacity';isReserved:boolean;unlockJobsRequired:number;capacity:number|null;color:string|null;active:boolean};
export { zoneCirclePolygon } from '~/lib/zone-circle';
type Point=[number,number];

export function ZoneMap({zones,selectedZoneId,onSelectZone,onDeleteZone,mode='view',tomtomKey,onGeometryChange}:{zones:ZoneMapItem[];selectedZoneId:string|null;onSelectZone:(id:string|null)=>void;onDeleteZone?: (id:string)=>void;mode?:'view'|'draw'|'edit';tomtomKey?:string;onGeometryChange?:(geometry:any)=>void}){
 const ref=useRef<HTMLDivElement>(null); const handles=useRef<HTMLDivElement>(null); const map=useRef<any>(null); const [unavailable,setUnavailable]=useState(false); const [tool,setTool]=useState<'draw'|'edit'|null>(null); const [points,setPoints]=useState<Point[]>([]); const drag=useRef<{index:number;midpoint:boolean}|null>(null); const frame=useRef<number|null>(null);
 const zonesRef=useRef(zones), selectedRef=useRef(selectedZoneId), pointsRef=useRef(points), toolRef=useRef(tool), selectRef=useRef(onSelectZone), geometryChangeRef=useRef(onGeometryChange); zonesRef.current=zones; selectedRef.current=selectedZoneId; pointsRef.current=points; toolRef.current=tool; selectRef.current=onSelectZone; geometryChangeRef.current=onGeometryChange;
 const selected=zones.find(z=>z.id===selectedZoneId);
 useEffect(()=>{let alive=true;(async()=>{if(!ref.current)return;const key=tomtomKey||(window as any).__LIGHTNING_TOMTOM_KEY__;if(!key){setUnavailable(true);return;}const sdk=await import('@tomtom-international/web-sdk-maps');if(!alive)return;const m=(sdk as any).default??sdk;const instance=m.map({key,container:ref.current,center:[-96,38],zoom:4});map.current=instance;instance.addControl(new m.NavigationControl());instance.on('load',()=>paint());instance.on('click',(e:any)=>{if(toolRef.current==='draw'){const p:[number,number]=[e.lngLat.lng,e.lngLat.lat];setPoints(old=>{if(old.length>=3&&Math.abs(old[0][0]-p[0])<.03&&Math.abs(old[0][1]-p[1])<.03){const ring=[...old,old[0]];geometryChangeRef.current?.({type:'Polygon',coordinates:[ring]});setTool(null);return old;}return [...old,p];});}});})();return()=>{alive=false;map.current?.remove();map.current=null}},[tomtomKey]);
 useEffect(()=>{pointsRef.current=points;if(map.current)paint()},[zones,selectedZoneId,points]);
 function paint(){const m=map.current;if(!m||typeof m.isStyleLoaded==='function'&&!m.isStyleLoaded())return;try{
  const features=zonesRef.current.map(z=>{const geometry=z.geometry??zoneCirclePolygon(z.lat,z.lng,z.radiusMiles);const demand=demandLevelToColor(z.demandLevel);return {type:'Feature',geometry,properties:{id:z.id,demandBucket:demand.label==='Low'?0:demand.label==='Medium'?1:demand.label==='High'?2:3,isReserved:z.isReserved===true||z.status==='reserved',reserved:z.status==='reserved',selected:z.id===selectedRef.current,active:z.active!==false,status:z.status}}});
  const data={type:'FeatureCollection',features};
  const source=m.getSource('zones');
  if(source) source.setData(data);
  else {
   m.addSource('zones',{type:'geojson',data});
   m.addLayer({id:'zones-fill',type:'fill',source:'zones',paint:{
    'fill-color':['case',['==',['get','active'],false],'#6B7280',['match',['get','demandBucket'],0,'#FDB268',1,'#F27801',2,'#DC2626',3,'#991B1B','#FDB268']],
    'fill-opacity':['case',['==',['get','active'],false],.12,['case',['get','selected'],.62,['match',['get','demandBucket'],0,.22,1,.32,2,.42,3,.54,.14]]]
   }});
   m.addLayer({id:'zones-outline',type:'line',source:'zones',paint:{
    'line-color':['case',['==',['get','active'],false],'#6B7280',['case',['get','selected'],'#F27801',['case',['get','isReserved'],'#F59E0B',['match',['get','status'],'at_capacity','#6B7280','busy','#DC2626','#16A34A']]]],
    'line-width':['case',['get','selected'],4,['case',['get','isReserved'],3,2]],'line-opacity':['case',['==',['get','active'],false],.35,1]
   }});
   m.addLayer({id:'zones-reserved',type:'line',source:'zones',filter:['==',['get','isReserved'],true],paint:{'line-color':'#F59E0B','line-width':3.5,'line-opacity':1}});
   m.addLayer({id:'zones-selected',type:'line',source:'zones',filter:['==',['get','selected'],true],paint:{'line-color':'#F27801','line-width':4,'line-opacity':1}});
   m.on('click','zones-fill',(e:any)=>{const id=e.features?.[0]?.properties?.id;if(id)selectRef.current(id)});
  }
  const drawSource=m.getSource('draw-preview');if(pointsRef.current.length>=2){const ring=pointsRef.current.length>=3?[...pointsRef.current,pointsRef.current[0]]:pointsRef.current;const drawData={type:'Feature',geometry:{type:'Polygon',coordinates:[ring]},properties:{}};if(drawSource)drawSource.setData(drawData);else{m.addSource('draw-preview',{type:'geojson',data:drawData});m.addLayer({id:'draw-fill',type:'fill',source:'draw-preview',paint:{'fill-color':'#F27801','fill-opacity':.18}});m.addLayer({id:'draw-line',type:'line',source:'draw-preview',paint:{'line-color':'#F27801','line-width':2,'line-dasharray':[2,2]}});}} else if(drawSource)drawSource.setData({type:'Feature',geometry:{type:'Polygon',coordinates:[[]]},properties:{}});
 }catch(error){console.error('Unable to paint zone polygons',error);}}
 const start=(t:'draw'|'edit')=>{setTool(t);if(t==='draw')setPoints([]);if(t==='edit'&&selected?.geometry){const r=selected.geometry.coordinates?.[0]??[];setPoints(r.slice(0,-1))}};
 const finish=()=>{setTool(null);setPoints([]);drag.current=null;if(frame.current)cancelAnimationFrame(frame.current)};
 function emit(next:Point[],final=false){setPoints(next);if(frame.current)cancelAnimationFrame(frame.current);frame.current=requestAnimationFrame(()=>{const ring=[...next,next[0]];geometryChangeRef.current?.({type:'Polygon',coordinates:[ring]});if(final)frame.current=null})}
 function moveDrag(e:React.PointerEvent){const d=drag.current;if(!d||!map.current||!ref.current)return;e.preventDefault();const rect=ref.current.getBoundingClientRect();const ll=map.current.unproject([e.clientX-rect.left,e.clientY-rect.top]);let next=[...pointsRef.current];if(d.midpoint){next.splice(d.index,0,[ll.lng,ll.lat]);drag.current={index:d.index,midpoint:false};}else next[d.index]=[ll.lng,ll.lat];emit(next)}
 function endDrag(){if(!drag.current)return;const next=[...pointsRef.current];geometryChangeRef.current?.({type:'Polygon',coordinates:[[...next,next[0]]]});drag.current=null}
 function renderHandles(){const el=handles.current,m=map.current;if(!el||!m||tool!=='edit'||points.length<3){if(el)el.replaceChildren();return;}el.replaceChildren();const add=(p:Point,index:number,midpoint:boolean)=>{const q=m.project({lng:p[0],lat:p[1]}),b=document.createElement('button');b.type='button';b.setAttribute('aria-label',midpoint?'Insert polygon vertex':'Move polygon vertex');b.style.cssText=`position:absolute;left:${q.x}px;top:${q.y}px;transform:translate(-50%,-50%);width:48px;height:48px;cursor:grab;background:transparent;border:0;padding:0;z-index:3;pointer-events:auto;`;const dot=document.createElement('span');dot.style.cssText=`display:block;margin:auto;width:${midpoint?10:12}px;height:${midpoint?10:12}px;border-radius:9999px;background:#fff;border:${midpoint?'2px solid #B3B3BB':'3px solid #F27801'};`;b.append(dot);b.onpointerdown=e=>{drag.current={index,midpoint};(e.currentTarget as HTMLElement).setPointerCapture?.(e.pointerId)};b.onpointermove=e=>moveDrag(e as any);b.onpointerup=endDrag;el.append(b)};points.forEach((p,i)=>{add(p,i,false);const n=points[(i+1)%points.length];add([(p[0]+n[0])/2,(p[1]+n[1])/2],i+1,true)})}
 useEffect(()=>{if(mode==='edit'&&selected?.geometry&&tool===null){const r=selected.geometry.coordinates?.[0]??[];setPoints(r.slice(0,-1));setTool('edit')}if(mode==='view')finish()},[mode,selectedZoneId]);
 useEffect(()=>{renderHandles();return()=>{handles.current?.replaceChildren();drag.current=null}},[tool,points,selectedZoneId]);
 return <div ref={ref} className="relative min-h-[360px] overflow-hidden rounded-2xl border border-ink-100 bg-ink-50" aria-label="Dispatch zone map"><div ref={handles} className="pointer-events-none absolute inset-0 z-20" onPointerMove={moveDrag} onPointerUp={endDrag}/>{unavailable&&<div className="absolute inset-0 z-20 grid place-items-center bg-ink-50 text-sm font-semibold text-ink-600">Map unavailable — configuration missing</div>}<div className="absolute left-3 top-3 z-10 rounded-xl border border-ink-100 bg-white p-3 text-xs shadow-[0_2px_8px_rgba(14,14,17,.10)]"><strong>Current demand</strong><div className="mt-2 grid grid-cols-4 gap-2">{[['#FDB268','Low'],['#F27801','Medium'],['#DC2626','High'],['#991B1B','Very high']].map(([c,l])=><span key={l} className="flex items-center gap-1"><i className="size-4 rounded-sm" style={{background:c}}/>{l}</span>)}</div></div>{mode!=='view'&&<div className="absolute right-3 top-3 z-10 flex gap-1 rounded-xl border border-ink-100 bg-white p-1 shadow"><Tool label="Draw polygon" active={tool==='draw'} onClick={()=>start('draw')}>＋</Tool><Tool label="Edit zone" active={tool==='edit'} onClick={()=>start('edit')}>✎</Tool><Tool label="Delete zone" onClick={()=>{if(selectedZoneId)onDeleteZone?.(selectedZoneId)}}>×</Tool><Tool label="Exit editing" onClick={finish}>↩</Tool></div>}{tool==='draw'&&<div className="absolute bottom-3 left-3 z-10 flex items-center gap-2 rounded-xl bg-white p-2 text-xs shadow">Tap 3+ points; tap first to close <button className="h-9 rounded-lg border px-3" onClick={finish}>Cancel</button></div>}</div>
}
function Tool({label,active,onClick,children}:{label:string;active?:boolean;onClick:()=>void;children:ReactNode}){return <button type="button" title={label} aria-label={label} onClick={onClick} className={`h-11 w-11 rounded-xl text-xl ${active?'bg-[#FFF4EA] text-[#B15000] ring-2 ring-inset ring-[#F27801]':''}`}>{children}</button>}
