import { useEffect, useRef, useState, type ReactNode } from 'react';
import { demandLevelToColor } from '~/lib/zone-model';
import '@tomtom-international/web-sdk-maps/dist/maps.css';
export type ZoneMapItem={id:string;name:string;state:string;market:string;geometry:any;lat:number;lng:number;radiusMiles:number;demandLevel:number|null;demandSource:'set'|'computed'|'unavailable';status:'available'|'busy'|'reserved'|'at_capacity';isReserved:boolean;unlockJobsRequired:number;capacity:number|null;color:string|null;active:boolean};
type Point=[number,number];
export function ZoneMap({zones,selectedZoneId,onSelectZone,mode='view',tomtomKey,onGeometryChange}:{zones:ZoneMapItem[];selectedZoneId:string|null;onSelectZone:(id:string|null)=>void;mode?:'view'|'draw'|'edit';tomtomKey?:string;onGeometryChange?:(geometry:any)=>void}){
 const ref=useRef<HTMLDivElement>(null); const map=useRef<any>(null); const layers=useRef<any[]>([]); const [unavailable,setUnavailable]=useState(false); const [tool,setTool]=useState<'draw'|'edit'|null>(null); const [points,setPoints]=useState<Point[]>([]);
 const selected=zones.find(z=>z.id===selectedZoneId);
 useEffect(()=>{let alive=true;(async()=>{if(!ref.current)return;const key=tomtomKey||(window as any).__LIGHTNING_TOMTOM_KEY__;if(!key){setUnavailable(true);return;}const sdk=await import('@tomtom-international/web-sdk-maps');if(!alive)return;const m=(sdk as any).default??sdk;map.current=m.map({key,container:ref.current,center:[-96,38],zoom:4});map.current.addControl(new m.NavigationControl());map.current.on('load',()=>paint());map.current.on('click',(e:any)=>{if(tool==='draw'){const p:[number,number]=[e.lngLat.lng,e.lngLat.lat];setPoints(old=>{if(old.length>=3&&Math.abs(old[0][0]-p[0])<.03&&Math.abs(old[0][1]-p[1])<.03){const ring=[...old,old[0]];onGeometryChange?.({type:'Polygon',coordinates:[ring]});setTool(null);return old;}return [...old,p];});}})})();return()=>{alive=false;map.current?.remove();map.current=null}},[tomtomKey,tool,onGeometryChange]);
 useEffect(()=>{if(map.current)paint()},[zones,selectedZoneId,points]);
 function paint(){const m=map.current;if(!m)return;for(const l of layers.current){try{m.removeLayer(l.id);m.removeSource(l.source)}catch{}}layers.current=[];zones.forEach(z=>{const g=z.geometry;if(!g)return;const source=`zone-${z.id}`,fill=`${source}-fill`,line=`${source}-line`;m.addSource(source,{type:'geojson',data:{type:'Feature',geometry:g,properties:{id:z.id}}});const base=demandLevelToColor(z.demandLevel),sel=z.id===selectedZoneId;m.addLayer({id:fill,type:'fill',source,paint:{'fill-color':z.color||base.hex,'fill-opacity':Math.min(.7,base.opacity+(sel?.1:0)),'fill-outline-color':'transparent'}});m.addLayer({id:line,type:'line',source,paint:{'line-color':sel?'#F27801':z.isReserved?'#F59E0B':z.status==='at_capacity'?'#B91C1C':z.status==='busy'?'#D96400':'#55555E','line-width':sel?4:z.isReserved||z.status==='at_capacity'?3:2,'line-opacity':1}});m.on('click',fill,()=>onSelectZone(z.id));layers.current.push({id:fill,source},{id:line,source})});if(points.length>=2){const id='draw-preview';const ring=points.length>=3?[...points,points[0]]:points;m.addSource(id,{type:'geojson',data:{type:'Feature',geometry:{type:'Polygon',coordinates:[ring]},properties:{}}});m.addLayer({id:'draw-fill',type:'fill',source:id,paint:{'fill-color':'#F27801','fill-opacity':.18}});m.addLayer({id:'draw-line',type:'line',source:id,paint:{'line-color':'#F27801','line-width':2,'line-dasharray':[2,2]}});layers.current.push({id:'draw-fill',source:id},{id:'draw-line',source:id})}}
 function start(t:'draw'|'edit'){setTool(t);if(t==='draw')setPoints([]);if(t==='edit'&&selected?.geometry){const r=selected.geometry.coordinates?.[0]??[];setPoints(r.slice(0,-1))}}
 function finish(){setTool(null);setPoints([])}
 return <div ref={ref} className="relative min-h-[360px] overflow-hidden rounded-2xl border border-ink-100 bg-ink-50" aria-label="Dispatch zone map">{unavailable&&<div className="absolute inset-0 z-20 grid place-items-center bg-ink-50 text-sm font-semibold text-ink-600">Map unavailable — configuration missing</div>}<div className="absolute left-3 top-3 z-10 rounded-xl border border-ink-100 bg-white p-3 text-xs shadow-[0_2px_8px_rgba(14,14,17,.10)]"><strong>Current demand</strong><div className="mt-2 grid grid-cols-4 gap-2">{[['#FDB268','Low'],['#F27801','Medium'],['#DC2626','High'],['#991B1B','Very high']].map(([c,l])=><span key={l} className="flex items-center gap-1"><i className="size-4 rounded-sm" style={{background:c}} />{l}</span>)}</div></div>{mode!=='view'&&<div className="absolute right-3 top-3 z-10 flex gap-1 rounded-xl border border-ink-100 bg-white p-1 shadow"><Tool label="Draw polygon" active={tool==='draw'} onClick={()=>start('draw')}>＋</Tool><Tool label="Edit zone" active={tool==='edit'} onClick={()=>start('edit')}>✎</Tool><Tool label="Delete zone" onClick={()=>onSelectZone(selectedZoneId)}>×</Tool><Tool label="Exit editing" onClick={finish}>↩</Tool></div>}{tool==='draw'&&<div className="absolute bottom-3 left-3 z-10 flex items-center gap-2 rounded-xl bg-white p-2 text-xs shadow">Tap 3+ points; tap first to close <button className="h-9 rounded-lg border px-3" onClick={finish}>Cancel</button></div>}</div>;
}
function Tool({label,active,onClick,children}:{label:string;active?:boolean;onClick:()=>void;children:ReactNode}){return <button type="button" title={label} aria-label={label} onClick={onClick} className={`h-11 w-11 rounded-xl text-xl ${active?'bg-[#FFF4EA] text-[#B15000] ring-2 ring-inset ring-[#F27801]':''}`}>{children}</button>}
