import { useEffect, useRef } from 'react';
import { useState } from 'react';
import { demandLevelToColor } from '~/lib/zone-model';
import '@tomtom-international/web-sdk-maps/dist/maps.css';
export type ZoneMapItem={id:string;name:string;state:string;market:string;geometry:any;lat:number;lng:number;radiusMiles:number;demandLevel:number|null;demandSource:'set'|'computed'|'unavailable';status:'available'|'busy'|'reserved'|'at_capacity';isReserved:boolean;unlockJobsRequired:number;capacity:number|null;color:string|null;active:boolean};
export function ZoneMap({zones,selectedZoneId,onSelectZone,mode='view',tomtomKey}:{zones:ZoneMapItem[];selectedZoneId:string|null;onSelectZone:(id:string|null)=>void;mode?:'view'|'draw'|'edit';tomtomKey?:string;onGeometryChange?:(geometry:any)=>void}){
 const ref=useRef<HTMLDivElement>(null); const map=useRef<any>(null); const layers=useRef<any[]>([]); const [unavailable,setUnavailable]=useState(false);
 useEffect(()=>{let alive=true; (async()=>{if(!ref.current)return; const key=tomtomKey || (window as any).__LIGHTNING_TOMTOM_KEY__ as string|undefined; if(!key){setUnavailable(true);return;} const sdk=await import('@tomtom-international/web-sdk-maps'); if(!alive)return; const m=(sdk as any).default??sdk; map.current=m.map({key,container:ref.current,center:[-96,38],zoom:4}); map.current.addControl(new m.NavigationControl()); map.current.on('load',()=>paint());})(); return()=>{alive=false;map.current?.remove();map.current=null};},[]);
 useEffect(()=>{if(map.current) paint()},[zones,selectedZoneId]);
 function paint(){const m=map.current;if(!m)return; for(const l of layers.current){try{m.removeLayer(l.id);m.removeSource(l.source)}catch{}} layers.current=[]; zones.forEach(z=>{const g=z.geometry;if(!g)return;const fc={type:'Feature',geometry:g,properties:{id:z.id}};const source=`zone-${z.id}`,fill=`${source}-fill`,line=`${source}-line`;m.addSource(source,{type:'geojson',data:fc});const base=demandLevelToColor(z.demandLevel);const opacity=Math.min(.7,base.opacity+(z.id===selectedZoneId?.1:0));m.addLayer({id:fill,type:'fill',source,paint:{'fill-color':z.color||base.hex,'fill-opacity':opacity,'fill-outline-color':'transparent'}});m.addLayer({id:line,type:'line',source,paint:{'line-color':z.id===selectedZoneId?'#F27801':z.isReserved?'#F59E0B':z.status==='at_capacity'?'#B91C1C':z.status==='busy'?'#D96400':'#55555E','line-width':z.id===selectedZoneId?4:z.isReserved||z.status==='at_capacity'?3:2}});m.on('click',fill,()=>onSelectZone(z.id));layers.current.push({id:fill,source},{id:line,source});});}
 return <div ref={ref} className="relative min-h-[360px] overflow-hidden rounded-2xl border border-ink-100 bg-ink-50" aria-label="Dispatch zone map">{unavailable&&<div className="absolute inset-0 z-20 grid place-items-center bg-ink-50 text-sm font-semibold text-ink-600">Map unavailable — configuration missing</div>}<div className="absolute left-3 top-3 z-10 rounded-xl border border-ink-100 bg-white p-3 text-xs shadow-[0_2px_8px_rgba(14,14,17,.10)]"><strong>Current demand</strong><div className="mt-2 grid grid-cols-4 gap-2">{[['#FDB268','Low'],['#F27801','Medium'],['#DC2626','High'],['#991B1B','Very high']].map(([c,l])=><span key={l} className="flex items-center gap-1"><i className="size-4 rounded-sm" style={{background:c}} />{l}</span>)}</div></div>{mode!=='view'&&<div className="absolute right-3 top-3 z-10 flex gap-1 rounded-xl border border-ink-100 bg-white p-1 shadow"><button className="h-11 w-11 rounded-xl" aria-label="Draw polygon">＋</button><button className="h-11 w-11 rounded-xl" aria-label="Edit zone">✎</button><button className="h-11 w-11 rounded-xl" aria-label="Exit editing">×</button></div>}</div>;
}
