import { createFileRoute } from "@tanstack/react-router";
import { useCallback, useEffect, useState } from "react";
import { Battery, Boxes, ClipboardCheck, FileClock, FileSpreadsheet, Gauge, Package } from "lucide-react";
import { AppShell } from "~/components/app-shell";
import { Button, Card, StatCard } from "~/components/ui";
import { getBatteryOwnerPortal, getBatterySaleDetail } from "~/data/battery-owner";
export const Route=createFileRoute("/owner/batteries")({component:BatteryManagement});
const money=(n:number|null|undefined)=>n==null?"—":`$${(n/100).toFixed(2)}`;
const date=(v:string|null|undefined)=>v?new Date(v).toLocaleDateString():"—";
function BatteryManagement(){
 const [data,setData]=useState<any>(null);const [sale,setSale]=useState<any>(null);const [tab,setTab]=useState("overview");const [denied,setDenied]=useState(false);
 const load=useCallback(async()=>{const r=await getBatteryOwnerPortal();if(!r.ok){setDenied(true);return;}setData(r);},[]);useEffect(()=>{void load()},[load]);
 if(denied)return <AppShell portal="owner" title="Battery management" description="Owner-only battery operations."><Card className="p-6"><h2 className="font-bold">Owner access required</h2><p className="mt-2 text-sm text-ink-500">This management surface is restricted to owner and admin accounts.</p></Card></AppShell>;
 if(!data)return <AppShell portal="owner" title="Battery management" description="Owner-only battery operations."><Card className="p-6">Loading battery operations…</Card></AppShell>;
 const r=data.reports;const tabs=[["overview","Overview",Gauge],["products","Products",Battery],["operations","Inventory & install",Boxes],["sales","Sales & warranties",Package],["compat","Compatibility",ClipboardCheck],["audit","Audit history",FileClock],["import","CSV import",FileSpreadsheet]] as const;
 return <AppShell portal="owner" title="Battery management" description="Lightning Gold Battery catalog, operations, payouts, warranties, and reporting."><div className="space-y-6"><div className="flex gap-2 overflow-x-auto pb-1">{tabs.map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className="inline-flex shrink-0 items-center gap-2 rounded-xl bg-surface px-3 py-2 text-sm font-bold text-ink-600 ring-1 ring-ink-100"><Icon size={15}/>{label}</button>)}</div>
 {tab==="overview"&&<Overview r={r}/>} {tab==="products"&&<Products rows={data.products}/>} {tab==="operations"&&<Operations inventory={data.inventory} installTypes={data.installTypes}/>} {tab==="sales"&&<Sales rows={data.sales} sale={sale} setSale={setSale}/>} {tab==="compat"&&<Compatibility rows={data.compatibility}/>} {tab==="audit"&&<Audit rows={data.audits}/>} {tab==="import"&&<Card className="p-5"><h2 className="text-lg font-bold">CSV import</h2><p className="mt-2 text-sm text-ink-500">Price book and compatibility imports validate all rows before the atomic owner-only write. Every import is recorded in audit history.</p><p className="mt-4 text-sm font-semibold">Lightning-only customer surfaces never receive internal cost, margin, or source references.</p></Card>}</div></AppShell>;
}
function Overview({r}:any){return <><section className="grid grid-cols-2 gap-3 lg:grid-cols-4"><StatCard label="Sales" value={r.summary.salesCount} detail="real battery sales"/><StatCard label="Revenue" value={money(r.summary.revenueCents)} detail="recorded totals"/><StatCard label="Completed installs" value={r.summary.completedInstallations} detail="real completion rows"/><StatCard label="Warranty expiring" value={r.warrantyExpiring90Days} detail="next 90 days"/></section><div className="grid gap-4 lg:grid-cols-2"><Report title="Sales funnel" rows={r.funnel.map((x:any)=>[x.status,String(x.count)])}/><Report title="Revenue by group" rows={r.byProduct.map((x:any)=>[x.groupSize,`${x.units} · ${money(x.revenueCents)}`])}/><Report title="Install types" rows={r.byInstallType.map((x:any)=>[x.installType,`${x.units} · ${money(x.revenueCents)}`])}/><Report title="Driver payouts" rows={r.payouts.map((x:any)=>[x.contractorName,`${x.installs} · ${money(x.payoutCents)}`])}/></div><Card className="p-4"><h3 className="font-bold">Inventory value</h3><p className="mt-2 text-sm">Retail value <strong>{money(r.inventoryValueCents)}</strong> · reorder needs <strong>{r.reorderCount}</strong></p></Card></>}
function Report({title,rows}:{title:string;rows:Array<[string,string]>}){return <Card className="p-4"><h3 className="font-bold">{title}</h3>{rows.map(([a,b],i)=><div key={i} className="mt-2 flex justify-between text-sm"><span className="text-ink-500">{a}</span><strong>{b}</strong></div>)}</Card>}
function Products({rows}:any){return <section className="space-y-3"><h2 className="text-lg font-bold">LIGHTNING GOLD BATTERY price book</h2>{rows.map((p:any)=><Card key={p.id} className="p-4"><p className="font-bold">{p.displayName} · GROUP {p.groupSize}</p><p className="text-sm text-ink-500">Customer price {money(p.retailCents)} · warranty {p.warrantyYears} years · {p.active?"Active":"Inactive"}</p><p className="text-xs text-ink-400">Updated {date(p.updatedAt)}</p></Card>)}</section>}
function Operations({inventory,installTypes}:any){return <div className="space-y-5"><section><h2 className="mb-3 text-lg font-bold">Inventory</h2>{inventory.map((x:any)=><Card key={x.id} className="mb-2 p-4"><div className="flex justify-between"><div><p className="font-bold">GROUP {x.groupSize}</p><p className="text-sm text-ink-500">Available {x.available} · reserved {x.reserved} · held {x.held}</p></div><strong>{x.onHand} on hand</strong></div>{x.lowStock&&<p className="mt-2 text-xs font-bold text-warning-700">REORDER REQUIRED · threshold {x.reorderThreshold}</p>}</Card>)}</section><section><h2 className="mb-3 text-lg font-bold">Installation pricing</h2>{installTypes.map((x:any)=><Card key={x.id} className="mb-2 p-4"><div className="flex justify-between gap-3"><div><p className="font-bold">{x.label}</p><p className="text-sm text-ink-500">{x.description} · {x.minutes} min</p></div><div className="text-right text-sm"><p>Customer {money(x.customerPriceCents)}</p><p className="font-bold">Driver payout {money(x.driverPayoutCents)}</p></div></div></Card>)}</section></div>}
function Sales({rows,sale,setSale}:any){return <section><h2 className="mb-3 text-lg font-bold">Sales, timelines, payouts & warranties</h2>{rows.map((x:any)=><Card key={x.id} className="mb-2 p-4"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-bold">{x.vehicle||"Vehicle unavailable"} · GROUP {x.groupSize||"—"}</p><p className="text-sm text-ink-500">{x.contractorName} · {x.status}</p><p className="text-xs text-ink-400">Battery {money(x.batteryCents)} · install {money(x.installCents)} · tax {money(x.taxCents)} · admin {money(x.adminFeeCents)} · total <strong>{money(x.totalCents)}</strong></p><p className="text-xs text-ink-400">Install job {x.installJobId||"—"} · payout {money(x.payoutCents)} · warranty {date(x.warrantyStartsAt)}–{date(x.warrantyExpiresAt)}</p></div><Button onClick={async()=>{const d=await getBatterySaleDetail({data:{saleId:x.id}});if(d.ok)setSale(d)}}>View detail</Button></div></Card>)}{sale&&<Card className="mt-4 border-brand-200 p-4"><div className="flex justify-between"><h3 className="font-bold">Sale detail · {sale.sale.vehicle}</h3><button onClick={()=>setSale(null)} className="text-sm text-ink-500">Close</button></div><h4 className="mt-4 font-bold">Status timeline</h4>{sale.timeline.map((x:any,i:number)=><p key={i} className="mt-2 text-sm">{date(x.at)} · {x.from} → {x.to}</p>)}<p className="mt-4 text-sm text-ink-500">{sale.photos.length} photos · {sale.audits.length} audit entries · payout {money(sale.sale.payout?.amountCents)}</p></Card>}</section>}
function Compatibility({rows}:any){return <section><h2 className="mb-3 text-lg font-bold">Compatibility dataset</h2>{rows.map((x:any)=><Card key={x.id} className="mb-2 p-3"><p className="font-semibold">{x.yearFrom}–{x.yearTo} {x.make} {x.model} · {x.groupSize}</p><p className="text-xs text-ink-400">{x.status} · {x.engine||"Any engine"} · {x.sourceReferenceInternal||"No provenance"}</p></Card>)}</section>}
function Audit({rows}:any){return <section><h2 className="mb-3 text-lg font-bold">Owner change history</h2>{rows.map((x:any)=><Card key={x.id} className="mb-2 p-3"><p className="text-sm font-semibold">{x.action} · {x.entityType} · {x.entityId}</p><p className="text-xs text-ink-400">{date(x.occurredAt)} · {x.actorRole} {x.actorUserId}</p><pre className="mt-2 overflow-x-auto text-xs text-ink-500">{JSON.stringify(x.detail)}</pre></Card>)}</section>}
