import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { AlertTriangle, Bell, Check, CheckCircle2, CircleDollarSign, Inbox, Zap } from "lucide-react";
import { useEffect, useState } from "react";
import { AppShell } from "~/components/app-shell";
import { listOwnerNotifications, markAllOwnerNotificationsRead, markOwnerNotificationRead, type OwnerNotification } from "~/data/owner-notifications";
export const Route=createFileRoute("/owner/notifications")({component:Notifications});
const icons:Record<string,typeof Bell>={escalation:AlertTriangle,job:Inbox,completed:CheckCircle2,cashout:CircleDollarSign};
const ago=(iso:string)=>{const n=Math.max(0,Date.now()-Date.parse(iso));if(n<60000)return "Just now";if(n<3600000)return `${Math.floor(n/60000)}m ago`;if(n<86400000)return `${Math.floor(n/3600000)}h ago`;return `${Math.floor(n/86400000)}d ago`;};
function Notifications(){const [rows,setRows]=useState<OwnerNotification[]>([]);const [busy,setBusy]=useState(false);const nav=useNavigate();const load=async()=>{const r=await listOwnerNotifications({data:{limit:100}});if(r.ok)setRows(r.data);};useEffect(()=>{void load();},[]);const read=async(n:OwnerNotification)=>{setRows(x=>x.map(v=>v.id===n.id?{...v,readAt:new Date().toISOString()}:v));await markOwnerNotificationRead({data:{id:n.id}});if(n.route)void nav({to:n.route as any});};const all=rows.filter(x=>!x.readAt).length;return <AppShell portal="owner" title="Notifications" description="Your durable owner activity feed."><div className="mb-5 flex items-center justify-between gap-3"><p className="text-sm font-semibold text-ink-500">{all} unread</p><button type="button" disabled={!all||busy} onClick={async()=>{setBusy(true);await markAllOwnerNotificationsRead();setRows(x=>x.map(n=>({...n,readAt:new Date().toISOString()})));setBusy(false);}} className="inline-flex h-10 items-center gap-2 rounded-xl border border-ink-200 px-3 text-xs font-bold text-ink-700 disabled:opacity-40"><Check className="size-4"/> Mark all read</button></div><div className="space-y-2">{rows.map(n=>{const Icon=icons[n.kind]??Zap;return <button key={n.id} type="button" onClick={()=>void read(n)} className={`flex w-full items-start gap-3 rounded-2xl border p-4 text-left transition-colors ${n.readAt?"border-ink-100 bg-surface":"border-brand-200 bg-brand-50/50"}`}><span className={`grid size-9 shrink-0 place-items-center rounded-xl ${n.kind==="escalation"?"bg-danger-100 text-danger-600":"bg-brand-100 text-brand-600"}`}><Icon className="size-4"/></span><span className="min-w-0 flex-1"><span className="flex items-center justify-between gap-3"><strong className="text-sm text-ink-900">{n.title}</strong><time className="shrink-0 text-[11px] text-ink-400">{ago(n.createdAt)}</time></span>{n.body&&<span className="mt-1 block text-xs leading-relaxed text-ink-500">{n.body}</span>}<span className="mt-2 block text-[10px] font-bold uppercase tracking-wider text-ink-400">{n.kind}{!n.readAt&&" · unread"}</span></span></button>})}</div>{!rows.length&&<div className="rounded-2xl border border-dashed border-ink-200 p-10 text-center text-sm text-ink-500">No notifications yet.</div>}</AppShell>}
