import { createFileRoute } from "@tanstack/react-router";
import { Plug, X, CheckCircle2, AlertTriangle, RefreshCw } from "lucide-react";
import { useEffect, useState, type FormEvent } from "react";
import { AppShell } from "~/components/app-shell";
import { Button, Card } from "~/components/ui";
import { connectTowbook, disconnectTowbook, towbookStatus, towbookSyncNow, type TowbookSyncResult } from "~/data/server";

export const Route = createFileRoute("/owner/settings")({ component: OwnerSettings });
function OwnerSettings() {
  const [open, setOpen] = useState(false), [username,setUsername]=useState(""), [password,setPassword]=useState("");
  const [status,setStatus]=useState<{connected:boolean;lastSyncAt:string|null}>({connected:false,lastSyncAt:null});
  const [pending,setPending]=useState(false), [error,setError]=useState(""), [success,setSuccess]=useState(false);
  const [sync,setSync]=useState<{pending:boolean;result:TowbookSyncResult|null}>({pending:false,result:null});
  const refresh=async()=>{const r=await towbookStatus();if(r.ok)setStatus({connected:!!r.connected,lastSyncAt:r.lastSyncAt});};
  useEffect(()=>{void refresh()},[]);
  const submit=async(e:FormEvent)=>{e.preventDefault();setPending(true);setError("");setSuccess(false);const r=await connectTowbook({data:{username,password}});setPending(false);if(r.ok){setPassword("");setOpen(false);setSuccess(true);void refresh()}else setError(r.error.message)};
  const disconnect=async()=>{setPending(true);const r=await disconnectTowbook();setPending(false);if(r.ok){setStatus({connected:false,lastSyncAt:null});setSuccess(false);setSync({pending:false,result:null})}else setError(r.error.message)};
  const syncNow=async()=>{setSync((s)=>({...s,pending:true}));const r=await towbookSyncNow();setSync({pending:false,result:r});void refresh()};
  return <AppShell title="Settings" description="Keep your organization and integrations connected.">
    <Card className="border-brand-200 bg-gradient-to-br from-brand-50/70 to-surface p-6 sm:p-8"><div className="flex flex-col gap-6 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-4"><span className="grid size-12 shrink-0 place-items-center rounded-2xl bg-brand-500 text-white"><Plug className="size-6" /></span><div><p className="text-xs font-bold uppercase tracking-wider text-brand-700">Dispatch integration</p><h2 className="mt-1 text-xl font-bold">Towbook</h2><p className="mt-1 max-w-lg text-sm text-ink-500">Bring live roadside jobs into Lightning Dispatch and keep your queue current.</p>{status.connected&&<p className="mt-3 flex items-center gap-2 text-sm font-semibold text-success-700"><CheckCircle2 className="size-4"/>Connected{status.lastSyncAt&&` · Last sync ${new Date(status.lastSyncAt).toLocaleString()}`}</p>}</div></div><div className="flex shrink-0 flex-col gap-2 sm:items-end">{status.connected?<div className="flex gap-2"><Button variant="secondary" onClick={syncNow} loading={sync.pending}><RefreshCw className="size-4"/>Sync now</Button><Button variant="ghost" className="border border-ink-200" onClick={disconnect} loading={pending}>Disconnect</Button></div>:<Button className="shrink-0" onClick={()=>{setOpen(true);setError("")}}>Connect Towbook</Button>}</div></div>
    {sync.result&&<div className={`mt-5 rounded-xl p-3 text-sm ${sync.result.ok?"bg-success-50 text-success-700":"bg-amber-50 text-amber-800"}`}><p className="flex items-start gap-2 font-semibold">{sync.result.ok?<CheckCircle2 className="mt-0.5 size-4 shrink-0"/>:<AlertTriangle className="mt-0.5 size-4 shrink-0"/>}{sync.result.message}</p>{sync.result.diagnostics.length>0&&<details className="mt-2"><summary className="cursor-pointer text-xs font-semibold text-ink-500">Sync diagnostics ({sync.result.diagnostics.length} probes)</summary><ul className="mt-2 max-h-48 space-y-1 overflow-y-auto font-mono text-[11px] leading-relaxed text-ink-500"><li className="text-emerald-700">✓ {sync.result.added} added · {sync.result.updated} updated · {sync.result.failed} failed</li>{sync.result.diagnostics.map((d,i)=>(<li key={i} className="truncate"><span className="font-bold">{d.status??"—"}</span> {d.url.replace("https://app.towbook.com","")||"/"} <span className="text-ink-400">— {d.hint}</span></li>))}</ul></details>}</div>}
    {success&&<p className="mt-5 rounded-xl bg-success-50 p-3 text-sm text-success-700">Towbook connected securely. The background puller can now use this session.</p>}{error&&!open&&<p className="mt-5 flex gap-2 rounded-xl bg-danger-50 p-3 text-sm text-danger-700"><AlertTriangle className="size-4 shrink-0"/>{error}</p>}</Card>
    {open&&<div className="fixed inset-0 z-50 grid place-items-center bg-ink-950/40 p-4" role="dialog" aria-modal="true" aria-labelledby="towbook-title"><Card className="w-full max-w-md p-6"><div className="flex items-start justify-between gap-4"><div><span className="grid size-10 place-items-center rounded-xl bg-brand-50 text-brand-600"><Plug className="size-5"/></span><h2 id="towbook-title" className="mt-4 text-xl font-bold">Connect Towbook</h2></div><button className="grid size-11 place-items-center rounded-xl text-ink-400 hover:bg-ink-50" aria-label="Close" onClick={()=>setOpen(false)}><X className="size-5"/></button></div><p className="mt-4 text-sm leading-relaxed text-ink-600">Enter your Towbook login once. Your password is used only to establish an encrypted session and is never stored.</p><form onSubmit={submit} className="mt-5 space-y-4"><label className="block text-sm font-semibold">Towbook username<input required type="text" value={username} onChange={e=>setUsername(e.target.value)} placeholder="e.g. mjohnson — often your email" className="mt-1 h-11 w-full rounded-xl border border-ink-200 px-3"/></label><label className="block text-sm font-semibold">Towbook password<input required type="password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-1 h-11 w-full rounded-xl border border-ink-200 px-3"/></label>{error&&<p className="flex gap-2 rounded-xl bg-danger-50 p-3 text-sm text-danger-700"><AlertTriangle className="size-4 shrink-0"/>{error}</p>}<Button type="submit" className="w-full" loading={pending}>Connect securely</Button></form></Card></div>}
  </AppShell>;
}
