import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { AppShell } from "~/components/app-shell";
import { Alert, BoardSkeleton, Button, Card, StatusBadge, useToast } from "~/components/ui";
import { getDispatchZonesForOwner, getOwnerZoneDriverRoster, ownerSetDriverZone, saveDispatchZone, deleteDispatchZone } from "~/data/zones";
import { ZoneMap } from "~/components/zone-map";
export const Route = createFileRoute("/owner/zones/")({ component: OwnerZones });
type ZoneType = "market"|"submarket"|"rural"|"corridor"|"coverage";
type Zone = { id:string; name:string; state:string; market:string; zoneType:ZoneType; zipCodes:string[]; parentZoneId:string|null; lat:number; lng:number; radiusMiles:number; tz:string; active:boolean; sortOrder:number; assignedDriverCount:number; polygonGeojson?:any; capacity:number|null; busyness:"Low"|"Moderate"|"Busy"; availableDrivers?:number; activeJobs?:number; jobsByZone?:number; availableDriversByZone?:number; marketId?:string|null; demandLevel?:number|null; demandSource?:'set'|'computed'|'unavailable'; status?:'available'|'busy'|'reserved'|'at_capacity'; isReserved?:boolean; unlockJobsRequired?:number; color?:string|null };
type Driver = { userId:string; name:string; active:boolean; online:boolean; zoneId:string|null; zoneName:string|null; zoneChangedAt:string|null };
const types:ZoneType[]=["market","submarket","rural","corridor","coverage"];
const blank:Partial<Zone>={name:"",state:"CT",market:"",zoneType:"market",zipCodes:[],parentZoneId:null,lat:0,lng:0,radiusMiles:10,tz:"America/New_York",sortOrder:0,active:false};
function DeleteConfirm({name,onCancel,onConfirm}:{name:string;onCancel:()=>void;onConfirm:()=>void}){return <div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4" role="dialog" aria-modal="true" aria-labelledby="delete-zone-title"><div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><h2 id="delete-zone-title" className="text-lg font-bold text-ink-900">Delete zone «{name}»?</h2><p className="mt-2 text-sm text-ink-600">This hides it from dispatch.</p><div className="mt-6 flex justify-end gap-2"><Button variant="secondary" onClick={onCancel}>Cancel</Button><Button variant="danger" onClick={onConfirm}>Delete zone</Button></div></div></div>}
function OwnerZones(){
 const toast=useToast(); const [zones,setZones]=useState<Zone[]|null>(null); const [savedSnapshot,setSavedSnapshot]=useState(""); const [saving,setSaving]=useState(false); const [colorError,setColorError]=useState(""); const [geometryError,setGeometryError]=useState(""); const [drivers,setDrivers]=useState<Driver[]>([]); const [error,setError]=useState(""); const [editing,setEditing]=useState<Partial<Zone>|null>(null); const [selected,setSelected]=useState(""); const [expanded,setExpanded]=useState<Record<string,boolean>>({});
 const visibleZones=zones?.filter(z=>z.zoneType!=="coverage"&&z.state!=="US")??[];
 const byState=[...new Set(visibleZones.map(z=>z.state))].sort();
 const load=async()=>{setError("");const [z,d]=await Promise.all([getDispatchZonesForOwner(),getOwnerZoneDriverRoster()]);if(z.ok)setZones(z.zones as Zone[]);else setError(z.message);if(d.ok)setDrivers(d.drivers as Driver[]);}; useEffect(()=>{void load();},[]);
 const update=(key:string,value:unknown)=>setEditing(e=>({...e,[key]:value}));
 const beginEdit=(z:Partial<Zone>)=>{setEditing(z);setSavedSnapshot(JSON.stringify(z));setColorError("");setGeometryError("");};
 const save=async()=>{if(!editing?.name||!editing.state||!editing.market){toast("Name, state, and market are required");return;}if(editing.color&&!/^#[0-9A-Fa-f]{6}$/.test(String(editing.color))){setColorError("Use a 6-digit hex color, e.g. #F27801");return;}const g=editing.polygonGeojson;if(g&&g.type==='Polygon'&&(!Array.isArray(g.coordinates?.[0])||g.coordinates[0].length<4)){setGeometryError("Polygon needs at least 3 valid points");return;}setSaving(true);const r=await saveDispatchZone({data:{id:editing.id,name:String(editing.name).trim(),state:String(editing.state).toUpperCase(),market:String(editing.market).trim(),marketId:editing.marketId??null,zoneType:editing.zoneType??"market",zipCodes:(editing.zipCodes??[]).map(String).map(x=>x.trim()).filter(Boolean),parentZoneId:editing.parentZoneId||null,lat:Number(editing.lat),lng:Number(editing.lng),radiusMiles:Number(editing.radiusMiles||10),tz:editing.tz||"America/New_York",active:editing.active??true,sortOrder:Number(editing.sortOrder||0),polygonGeojson:editing.polygonGeojson??null,capacity:editing.capacity==null||String(editing.capacity)===""?null:Number(editing.capacity),demandLevel:editing.demandLevel==null||String(editing.demandLevel)===''?null:Number(editing.demandLevel),status:editing.status??"available",isReserved:Boolean(editing.isReserved),unlockJobsRequired:editing.isReserved?Number(editing.unlockJobsRequired??30):0,color:editing.color||null}});if(!r.ok){setSaving(false);toast(r.message);return;}toast("Zone saved");setSaving(false);setEditing(null);setSavedSnapshot("");void load();};
 const override=async(zoneId:string|null)=>{if(!selected)return;const r=await ownerSetDriverZone({data:{userId:selected,zoneId}});if(!r.ok)toast(r.message);else{toast("Driver zone updated");void load();}};
 const [deleteTarget,setDeleteTarget]=useState<Zone|null>(null);
 const remove=async()=>{if(!deleteTarget)return;const r=await deleteDispatchZone({data:{zoneId:deleteTarget.id}});if(!r.ok){toast(r.message);return;}toast("Zone deleted");setDeleteTarget(null);setEditing(null);void load();};
 return <AppShell portal="owner" title="Zones" description="Configure national dispatch markets and driver zone assignments.">{error&&<Alert variant="danger">{error}</Alert>}{!zones?<BoardSkeleton rows={3}/>:<div className="space-y-5"><ZoneMap zones={visibleZones.map(z=>({id:z.id,name:z.name,state:z.state,market:z.market,geometry:z.polygonGeojson??null,lat:z.lat,lng:z.lng,radiusMiles:z.radiusMiles,demandLevel:z.demandLevel??null,demandSource:z.demandSource??'unavailable',status:z.status??'available',isReserved:z.isReserved??false,unlockJobsRequired:z.unlockJobsRequired??30,capacity:z.capacity,color:z.color??null,active:z.active}))} selectedZoneId={editing?.id??null} onSelectZone={id=>{if(id){const z=visibleZones.find(x=>x.id===id);if(z)beginEdit({...z});}else setEditing(null)}} mode={editing?'edit':'view'} onDeleteZone={id=>{const z=visibleZones.find(x=>x.id===id);if(z)setDeleteTarget(z);}} onGeometryChange={g=>update("polygonGeojson",g)} />{geometryError&&<span className="mt-1 block text-xs font-semibold text-red-600">{geometryError}</span>}<div className="flex justify-end"><Button onClick={()=>{setEditing({...blank});setSavedSnapshot("");setColorError("");setGeometryError("")}}>Create zone</Button></div>
 {editing&&<Card className="p-4"><h2 className="font-bold">{editing.id?"Edit zone":"New zone"}</h2><div className="mt-3 grid gap-3 sm:grid-cols-2">
  <Field label="Name" value={editing.name??""} onChange={v=>update("name",v)}/><Field label="State (2 letters)" value={editing.state??""} onChange={v=>update("state",v.toUpperCase())}/><Field label="Market" value={editing.market??""} onChange={v=>update("market",v)}/><label className="text-xs font-semibold text-ink-600">Demand level <span className="float-right tabular-nums">{editing.demandLevel==null?"Demand unavailable":`${editing.demandLevel}/100`}</span><input type="range" min="0" max="100" step="1" value={editing.demandLevel??0} onChange={e=>update("demandLevel",Number(e.target.value))} className="mt-3 w-full accent-[#F27801]" /><button type="button" className="mt-1 text-xs font-semibold text-accent-700 underline" onClick={()=>update("demandLevel",null)}>Unset</button></label><label className="text-xs font-semibold text-ink-600">Status<select value={editing.status??"available"} onChange={e=>update("status",e.target.value)} className="mt-1 h-11 w-full rounded-xl border border-ink-200 px-3 text-sm">{["available","busy","reserved","at_capacity"].map(s=><option key={s}>{s}</option>)}</select></label><label className="flex h-11 items-center gap-3 text-sm font-semibold"><span className={`relative inline-flex h-6 w-11 shrink-0 rounded-full transition-colors ${editing.isReserved?'bg-[#F59E0B]':'bg-[#B3B3BB]'}`} role="switch" aria-checked={Boolean(editing.isReserved)} tabIndex={0} onClick={()=>update("isReserved",!editing.isReserved)}><span className={`absolute top-1 size-4 rounded-full bg-white transition-transform ${editing.isReserved?'translate-x-6':'translate-x-1'}`} /></span> 🔒 Reserved zone</label>{editing.isReserved&&<label className="text-xs font-semibold text-ink-600">Unlock jobs required<input type="number" min="0" step="1" value={editing.unlockJobsRequired??30} onChange={e=>update("unlockJobsRequired",Number(e.target.value))} className="mt-1 h-11 w-full rounded-xl border border-ink-200 px-3 text-sm" /><span className="font-normal text-ink-500">Completed roadside jobs</span></label>}<label className="text-xs font-semibold text-ink-600">Color override <span className="font-normal text-ink-400">Auto (demand)</span><div className="mt-1 flex gap-2"><input value={editing.color??""} placeholder="#RRGGBB" onChange={e=>{setColorError("");update("color",e.target.value||null)}} className="h-11 flex-1 rounded-xl border border-ink-200 px-3 text-sm" />{editing.color&&<i className="size-6 self-center rounded-full border" style={{background:editing.color}} />}</div>{colorError&&<span className="mt-1 block text-xs font-normal text-red-600">{colorError}</span>}</label>
  <label className="text-xs font-semibold text-ink-600">Zone type<select value={editing.zoneType??"market"} onChange={e=>update("zoneType",e.target.value)} className="mt-1 h-11 w-full rounded-xl border border-ink-200 px-3 text-sm">{types.map(t=><option key={t}>{t}</option>)}</select></label>
  <Field label="ZIP codes (comma separated)" value={(editing.zipCodes??[]).join(", ")} onChange={v=>update("zipCodes",v.split(",").map(x=>x.trim()).filter(Boolean))}/>
  <label className="text-xs font-semibold text-ink-600">Parent zone<select value={editing.parentZoneId??""} onChange={e=>update("parentZoneId",e.target.value||null)} className="mt-1 h-11 w-full rounded-xl border border-ink-200 px-3 text-sm"><option value="">Root / US</option>{zones.filter(z=>z.id!==editing.id&&(z.zoneType==="coverage"||z.state==="US")).map(z=><option key={z.id} value={z.id}>{z.name} · {z.zoneType} · {z.state}</option>)}</select></label>
  <Field label="Latitude" value={editing.lat??0} onChange={v=>update("lat",v)}/><Field label="Longitude" value={editing.lng??0} onChange={v=>update("lng",v)}/><Field label="Radius (miles)" value={editing.radiusMiles??10} onChange={v=>update("radiusMiles",v)}/><Field label="Capacity (blank = no cap)" value={editing.capacity??""} onChange={v=>update("capacity",v)}/><label className="text-xs font-semibold text-ink-600 sm:col-span-2">GeoJSON Polygon / MultiPolygon<textarea value={typeof editing.polygonGeojson==='string'?editing.polygonGeojson:editing.polygonGeojson?JSON.stringify(editing.polygonGeojson):""} onChange={e=>{try{update("polygonGeojson",e.target.value?JSON.parse(e.target.value):null)}catch{update("polygonGeojson",e.target.value)}}} className="mt-1 min-h-28 w-full rounded-xl border border-ink-200 p-3 font-mono text-xs" placeholder='{"type":"Polygon","coordinates":[...]}' /></label><Field label="Time zone" value={editing.tz??"America/New_York"} onChange={v=>update("tz",v)}/><Field label="Sort order" value={editing.sortOrder??0} onChange={v=>update("sortOrder",v)}/>
  <label className="flex items-center gap-2 self-end pb-2 text-sm font-semibold"><input type="checkbox" checked={editing.active??true} onChange={e=>update("active",e.target.checked)}/> Active</label>
 </div><div className="mt-4 flex items-center gap-3"><span className="mr-auto text-xs font-semibold text-ink-500">{savedSnapshot && JSON.stringify(editing)!==savedSnapshot?"Unsaved changes":""}</span><Button onClick={()=>void save()} disabled={saving}>{saving?"Saving…":"Save zone"}</Button><Button variant="secondary" onClick={()=>setEditing(null)}>Cancel</Button></div></Card>}
 <div className="space-y-3">{byState.map(state=>{const stateZones=visibleZones.filter(z=>z.state===state); const open=expanded[state]??false; return <section key={state} className="overflow-hidden rounded-2xl border border-ink-200 bg-surface"><button type="button" onClick={()=>setExpanded(e=>({...e,[state]:!open}))} className="flex min-h-16 w-full items-center justify-between gap-3 px-4 py-3 text-left hover:bg-ink-50"><span className="font-bold text-ink-800">{state} <span className="font-normal text-ink-500">· {stateZones.length} zones · {stateZones.filter(z=>z.active).length} active</span></span><span className="text-xl text-ink-400">{open?"−":"+"}</span></button>{open&&<div className="grid gap-3 border-t border-ink-100 p-3">{stateZones.map(z=><Card key={z.id} className="p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h2 className="font-bold">{z.name}</h2><StatusBadge className={z.active?"bg-success-50 text-success-700":"bg-ink-100 text-ink-500"}>{z.active?"Active":"Inactive"}</StatusBadge><StatusBadge className="bg-accent-50 text-accent-800">{z.zoneType}</StatusBadge><StatusBadge className={z.busyness==="Busy"?"bg-danger-50 text-danger-700":z.busyness==="Moderate"?"bg-accent-50 text-accent-800":"bg-success-50 text-success-700"}>{z.busyness}</StatusBadge></div><p className="mt-2 text-sm text-ink-600">{z.state}{z.market?` · ${z.market}`:""} · <strong className="text-ink-900">{z.zipCodes.length} ZIPs</strong>{z.zipCodes.length?` · ${z.zipCodes.slice(0,3).join(", ")}${z.zipCodes.length>3?" …":""}`:""}{z.parentZoneId?` · parent: ${zones.find(p=>p.id===z.parentZoneId)?.name??"—"}`:" · root"}</p><p className="mt-1 text-xs text-ink-500">{z.assignedDriverCount} assigned · {z.availableDrivers??0} available · {z.activeJobs??0} active jobs · {z.jobsByZone??0} calls in 24h</p><p className="mt-1 text-xs text-ink-400">{z.lat}, {z.lng} · {z.radiusMiles} mi · {z.tz} · sort {z.sortOrder}</p></div><div className="flex gap-2"><Button size="sm" variant="secondary" onClick={()=>setEditing({...z})}>Edit</Button><Button size="sm" variant="secondary" onClick={async()=>{const r=await saveDispatchZone({data:{...z,zoneType:z.zoneType,zipCodes:z.zipCodes,parentZoneId:z.parentZoneId,active:!z.active}});if(!r.ok)toast(r.message);else void load();}}>{z.active?"Disable":"Enable"}</Button></div></div></Card>)}</div>}</section>})} </div>
 <Card className="p-4"><h2 className="font-bold">Driver zone overrides</h2><p className="mt-1 text-xs text-ink-500">Owner overrides bypass the daily change limit.</p><div className="mt-3 grid gap-3 sm:grid-cols-2"><select value={selected} onChange={e=>setSelected(e.target.value)} className="h-11 rounded-xl border border-ink-200 px-3 text-sm"><option value="">Select driver</option>{drivers.map(d=><option key={d.userId} value={d.userId}>{d.name}{d.online?" · online":""}</option>)}</select><select disabled={!selected} onChange={e=>void override(e.target.value||null)} className="h-11 rounded-xl border border-ink-200 px-3 text-sm"><option value="">Clear zone</option>{zones.filter(z=>z.active&&z.zoneType!=="coverage").map(z=><option key={z.id} value={z.id}>{z.name}</option>)}</select></div></Card></div>}{deleteTarget&&<DeleteConfirm name={deleteTarget.name} onCancel={()=>setDeleteTarget(null)} onConfirm={()=>void remove()}/>}</AppShell>;
}
function Field({label,value,onChange}:{label:string;value:unknown;onChange:(v:string)=>void}){return <label className="text-xs font-semibold text-ink-600">{label}<input value={String(value??"")} onChange={e=>onChange(e.target.value)} className="mt-1 h-11 w-full rounded-xl border border-ink-200 px-3 text-sm" /></label>}
