import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { AppShell } from "~/components/app-shell";
import { Alert, BoardSkeleton, Button, Card, StatusBadge, useToast } from "~/components/ui";
import { getDispatchZonesForOwner, getOwnerZoneDriverRoster, ownerSetDriverZone, saveDispatchZone } from "~/data/zones";
export const Route = createFileRoute("/owner/zones/")({ component: OwnerZones });
type Zone = { id: string; name: string; lat: number; lng: number; radiusMiles: number; tz: string; active: boolean; sortOrder: number; assignedDriverCount: number; busyness: "Low" | "Moderate" | "Busy"; availableDrivers?: number; activeJobs?: number };
type Driver = { userId: string; name: string; active: boolean; online: boolean; zoneId: string | null; zoneName: string | null; zoneChangedAt: string | null };
function OwnerZones() { const toast = useToast(); const [zones,setZones]=useState<Zone[]|null>(null); const [drivers,setDrivers]=useState<Driver[]>([]); const [error,setError]=useState(""); const [editing,setEditing]=useState<Partial<Zone>|null>(null); const [selected,setSelected]=useState("");
 const load=async()=>{const [z,d]=await Promise.all([getDispatchZonesForOwner(),getOwnerZoneDriverRoster()]); if(z.ok)setZones(z.zones as Zone[]); else setError(z.message); if(d.ok)setDrivers(d.drivers as Driver[]);}; useEffect(()=>{void load();},[]);
 const save=async()=>{if(!editing?.name)return; const r=await saveDispatchZone({data:{id:editing.id,name:editing.name,lat:Number(editing.lat),lng:Number(editing.lng),radiusMiles:Number(editing.radiusMiles||10),tz:editing.tz||"America/New_York",active:editing.active??true,sortOrder:Number(editing.sortOrder||0)}}); if(!r.ok){toast(r.message);return;} toast("Zone saved");setEditing(null);void load();};
 const override=async(zoneId:string|null)=>{if(!selected)return;const r=await ownerSetDriverZone({data:{userId:selected,zoneId}});if(!r.ok)toast(r.message);else{toast("Driver zone updated");void load();}};
 return <AppShell portal="owner" title="Zones" description="Configure dispatch markets and driver zone assignments.">{error&&<Alert variant="danger">{error}</Alert>}{!zones?<BoardSkeleton rows={3}/>:<div className="space-y-5"><div className="flex justify-end"><Button onClick={()=>setEditing({active:true,radiusMiles:10,tz:"America/New_York",sortOrder:0,lat:0,lng:0})}>Create zone</Button></div>{editing&&<Card className="p-4"><h2 className="font-bold">{editing.id?"Edit zone":"New zone"}</h2><div className="mt-3 grid gap-3 sm:grid-cols-2">{(["name","lat","lng","radiusMiles","tz","sortOrder"] as const).map(k=><label key={k} className="text-xs font-semibold text-ink-600">{k}<input value={String(editing[k]??"")} onChange={e=>setEditing({...editing,[k]:e.target.value})} className="mt-1 h-11 w-full rounded-xl border border-ink-200 px-3 text-sm" /></label>)}</div><div className="mt-4 flex gap-2"><Button onClick={()=>void save()}>Save</Button><Button variant="secondary" onClick={()=>setEditing(null)}>Cancel</Button></div></Card>}
 <div className="grid gap-3">{zones.map(z=><Card key={z.id} className="p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><h2 className="font-bold">{z.name}</h2><StatusBadge className={z.active?"bg-success-50 text-success-700":"bg-ink-100 text-ink-500"}>{z.active?"Active":"Inactive"}</StatusBadge><StatusBadge className="bg-accent-50 text-accent-800">{z.busyness}</StatusBadge></div><p className="mt-2 text-xs text-ink-500">{z.lat}, {z.lng} · {z.radiusMiles} mi · {z.tz}</p><p className="mt-1 text-xs text-ink-500">{z.assignedDriverCount} assigned · {z.availableDrivers??0} available</p></div><div className="flex gap-2"><Button size="sm" variant="secondary" onClick={()=>setEditing(z)}>Edit</Button><Button size="sm" variant="secondary" onClick={async()=>{const r=await saveDispatchZone({data:{id:z.id,name:z.name,lat:z.lat,lng:z.lng,radiusMiles:z.radiusMiles,tz:z.tz,active:!z.active,sortOrder:z.sortOrder}});if(!r.ok)toast(r.message);else void load();}}>{z.active?"Disable zone":"Enable zone"}</Button></div></div></Card>)}</div>
 <Card className="p-4"><h2 className="font-bold">Driver zone overrides</h2><p className="mt-1 text-xs text-ink-500">Owner overrides bypass the daily change limit.</p><div className="mt-3 grid gap-3 sm:grid-cols-2"><select value={selected} onChange={e=>setSelected(e.target.value)} className="h-11 rounded-xl border border-ink-200 px-3 text-sm"><option value="">Select driver</option>{drivers.map(d=><option key={d.userId} value={d.userId}>{d.name}{d.online?" · online":""}</option>)}</select><select disabled={!selected} onChange={e=>void override(e.target.value||null)} className="h-11 rounded-xl border border-ink-200 px-3 text-sm"><option value="">Clear zone</option>{zones.filter(z=>z.active).map(z=><option key={z.id} value={z.id}>{z.name}</option>)}</select></div></Card></div>}</AppShell> }
