import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { AppShell } from "~/components/app-shell";
import { Alert, BoardSkeleton, Button, Card, StatusBadge, useToast } from "~/components/ui";
import { getDispatchZonesForOwner, getOwnerZoneDriverRoster, ownerSetDriverZone, saveDispatchZone } from "~/data/zones";
export const Route = createFileRoute("/owner/zones/")({ component: OwnerZones });
type ZoneType = "market"|"submarket"|"rural"|"corridor"|"coverage";
type Zone = { id:string; name:string; state:string; market:string; zoneType:ZoneType; zipCodes:string[]; parentZoneId:string|null; lat:number; lng:number; radiusMiles:number; tz:string; active:boolean; sortOrder:number; assignedDriverCount:number; busyness:"Low"|"Moderate"|"Busy"; availableDrivers?:number; activeJobs?:number; jobsByZone?:number; availableDriversByZone?:number };
type Driver = { userId:string; name:string; active:boolean; online:boolean; zoneId:string|null; zoneName:string|null; zoneChangedAt:string|null };
const types:ZoneType[]=["market","submarket","rural","corridor","coverage"];
 const visibleZones=zones?.filter(z=>z.zoneType!=="coverage"&&z.state!=="US")??[];
 const byState=[...new Set(visibleZones.map(z=>z.state))].sort();
const blank:Partial<Zone>={name:"",state:"CT",market:"",zoneType:"market",zipCodes:[],parentZoneId:null,lat:0,lng:0,radiusMiles:10,tz:"America/New_York",sortOrder:0,active:true};
function OwnerZones(){
 const toast=useToast(); const [zones,setZones]=useState<Zone[]|null>(null); const [drivers,setDrivers]=useState<Driver[]>([]); const [error,setError]=useState(""); const [editing,setEditing]=useState<Partial<Zone>|null>(null); const [selected,setSelected]=useState("");
 const load=async()=>{setError("");const [z,d]=await Promise.all([getDispatchZonesForOwner(),getOwnerZoneDriverRoster()]);if(z.ok)setZones(z.zones as Zone[]);else setError(z.message);if(d.ok)setDrivers(d.drivers as Driver[]);}; useEffect(()=>{void load();},[]);
 const update=(key:string,value:unknown)=>setEditing(e=>({...e,[key]:value}));
 const save=async()=>{if(!editing?.name||!editing.state){toast("Name and state are required");return;}const r=await saveDispatchZone({data:{id:editing.id,name:String(editing.name).trim(),state:String(editing.state).toUpperCase(),market:String(editing.market??"").trim(),zoneType:editing.zoneType??"market",zipCodes:(editing.zipCodes??[]).map(String).map(x=>x.trim()).filter(Boolean),parentZoneId:editing.parentZoneId||null,lat:Number(editing.lat),lng:Number(editing.lng),radiusMiles:Number(editing.radiusMiles||10),tz:editing.tz||"America/New_York",active:editing.active??true,sortOrder:Number(editing.sortOrder||0)}});if(!r.ok){toast(r.message);return;}toast("Zone saved");setEditing(null);void load();};
 const override=async(zoneId:string|null)=>{if(!selected)return;const r=await ownerSetDriverZone({data:{userId:selected,zoneId}});if(!r.ok)toast(r.message);else{toast("Driver zone updated");void load();}};
 return <AppShell portal="owner" title="Zones" description="Configure national dispatch markets and driver zone assignments.">{error&&<Alert variant="danger">{error}</Alert>}{!zones?<BoardSkeleton rows={3}/>:<div className="space-y-5"><div className="flex justify-end"><Button onClick={()=>setEditing({...blank})}>Create zone</Button></div>
 {editing&&<Card className="p-4"><h2 className="font-bold">{editing.id?"Edit zone":"New zone"}</h2><div className="mt-3 grid gap-3 sm:grid-cols-2">
  <Field label="Name" value={editing.name??""} onChange={v=>update("name",v)}/><Field label="State (2 letters)" value={editing.state??""} onChange={v=>update("state",v.toUpperCase())}/><Field label="Market" value={editing.market??""} onChange={v=>update("market",v)}/>
  <label className="text-xs font-semibold text-ink-600">Zone type<select value={editing.zoneType??"market"} onChange={e=>update("zoneType",e.target.value)} className="mt-1 h-11 w-full rounded-xl border border-ink-200 px-3 text-sm">{types.map(t=><option key={t}>{t}</option>)}</select></label>
  <Field label="ZIP codes (comma separated)" value={(editing.zipCodes??[]).join(", ")} onChange={v=>update("zipCodes",v.split(",").map(x=>x.trim()).filter(Boolean))}/>
  <label className="text-xs font-semibold text-ink-600">Parent zone<select value={editing.parentZoneId??""} onChange={e=>update("parentZoneId",e.target.value||null)} className="mt-1 h-11 w-full rounded-xl border border-ink-200 px-3 text-sm"><option value="">Root / US</option>{zones.filter(z=>z.id!==editing.id&&(z.zoneType==="coverage"||z.state==="US")).map(z=><option key={z.id} value={z.id}>{z.name} · {z.zoneType} · {z.state}</option>)}</select></label>
  <Field label="Latitude" value={editing.lat??0} onChange={v=>update("lat",v)}/><Field label="Longitude" value={editing.lng??0} onChange={v=>update("lng",v)}/><Field label="Radius (miles)" value={editing.radiusMiles??10} onChange={v=>update("radiusMiles",v)}/><Field label="Time zone" value={editing.tz??"America/New_York"} onChange={v=>update("tz",v)}/><Field label="Sort order" value={editing.sortOrder??0} onChange={v=>update("sortOrder",v)}/>
  <label className="flex items-center gap-2 self-end pb-2 text-sm font-semibold"><input type="checkbox" checked={editing.active??true} onChange={e=>update("active",e.target.checked)}/> Active</label>
 </div><div className="mt-4 flex gap-2"><Button onClick={()=>void save()}>Save zone</Button><Button variant="secondary" onClick={()=>setEditing(null)}>Cancel</Button></div></Card>}
 <div className="space-y-6">{byState.map(state=><section key={state}><h2 className="mb-3 border-b border-ink-200 pb-2 text-lg font-bold text-ink-800">{state}</h2><div className="grid gap-3 pl-3">{visibleZones.filter(z=>z.state===state).map(z=><Card key={z.id} className="p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h2 className="font-bold">{z.name}</h2><StatusBadge className={z.active?"bg-success-50 text-success-700":"bg-ink-100 text-ink-500"}>{z.active?"Active":"Inactive"}</StatusBadge><StatusBadge className="bg-accent-50 text-accent-800">{z.zoneType}</StatusBadge><StatusBadge className={z.busyness==="Busy"?"bg-danger-50 text-danger-700":z.busyness==="Moderate"?"bg-accent-50 text-accent-800":"bg-success-50 text-success-700"}>{z.busyness}</StatusBadge></div><p className="mt-2 text-sm text-ink-600">{z.state}{z.market?` · ${z.market}`:""} · <strong className="text-ink-900">{z.zipCodes.length} ZIPs</strong>{z.zipCodes.length?` · ${z.zipCodes.slice(0,3).join(", ")}${z.zipCodes.length>3?" …":""}`:""}{z.parentZoneId?` · parent: ${zones.find(p=>p.id===z.parentZoneId)?.name??"—"}`:" · root"}</p><p className="mt-1 text-xs text-ink-500">{z.assignedDriverCount} assigned · {z.availableDrivers??0} available · {z.activeJobs??0} active jobs · {z.jobsByZone??0} calls in 24h</p><p className="mt-1 text-xs text-ink-400">{z.lat}, {z.lng} · {z.radiusMiles} mi · {z.tz} · sort {z.sortOrder}</p></div><div className="flex gap-2"><Button size="sm" variant="secondary" onClick={()=>setEditing({...z})}>Edit</Button><Button size="sm" variant="secondary" onClick={async()=>{const r=await saveDispatchZone({data:{...z,zoneType:z.zoneType,zipCodes:z.zipCodes,parentZoneId:z.parentZoneId,active:!z.active}});if(!r.ok)toast(r.message);else void load();}}>{z.active?"Disable":"Enable"}</Button></div></div></Card>)}</div></div>)} </div>
 <Card className="p-4"><h2 className="font-bold">Driver zone overrides</h2><p className="mt-1 text-xs text-ink-500">Owner overrides bypass the daily change limit.</p><div className="mt-3 grid gap-3 sm:grid-cols-2"><select value={selected} onChange={e=>setSelected(e.target.value)} className="h-11 rounded-xl border border-ink-200 px-3 text-sm"><option value="">Select driver</option>{drivers.map(d=><option key={d.userId} value={d.userId}>{d.name}{d.online?" · online":""}</option>)}</select><select disabled={!selected} onChange={e=>void override(e.target.value||null)} className="h-11 rounded-xl border border-ink-200 px-3 text-sm"><option value="">Clear zone</option>{zones.filter(z=>z.active&&z.zoneType!=="coverage").map(z=><option key={z.id} value={z.id}>{z.name}</option>)}</select></div></Card></div>}</AppShell>;
}
function Field({label,value,onChange}:{label:string;value:unknown;onChange:(v:string)=>void}){return <label className="text-xs font-semibold text-ink-600">{label}<input value={String(value??"")} onChange={e=>onChange(e.target.value)} className="mt-1 h-11 w-full rounded-xl border border-ink-200 px-3 text-sm" /></label>}
