/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as ContractorRouteImport } from './routes/contractor'
import { Route as R403RouteImport } from './routes/403'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OwnerIndexRouteImport } from './routes/owner/index'
import { Route as OpsIndexRouteImport } from './routes/ops/index'
import { Route as DriverIndexRouteImport } from './routes/driver/index'
import { Route as OwnerSettingsRouteImport } from './routes/owner/settings'
import { Route as OwnerQueueRouteImport } from './routes/owner/queue'
import { Route as OwnerPerformanceRouteImport } from './routes/owner/performance'
import { Route as OwnerMoneyRouteImport } from './routes/owner/money'
import { Route as OwnerHistoryRouteImport } from './routes/owner/history'
import { Route as OwnerDriversRouteImport } from './routes/owner/drivers'
import { Route as OwnerContractorsRouteImport } from './routes/owner/contractors'
import { Route as OwnerContractorsIdRouteImport } from './routes/owner/contractors.$id'
import { Route as OwnerAiDispatcherRouteImport } from './routes/owner/ai-dispatcher'
import { Route as OwnerActiveRouteImport } from './routes/owner/active'
import { Route as OpsHistoryRouteImport } from './routes/ops/history'
import { Route as OpsContractorsRouteImport } from './routes/ops/contractors'
import { Route as OpsActiveRouteImport } from './routes/ops/active'
import { Route as DriverProfileRouteImport } from './routes/driver/profile'
import { Route as DriverOffersRouteImport } from './routes/driver/offers'
import { Route as DriverHelpRouteImport } from './routes/driver/help'
import { Route as DriverEarningsRouteImport } from './routes/driver/earnings'
import { Route as DriverActiveRouteImport } from './routes/driver/active'

const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractorRoute = ContractorRouteImport.update({
  id: '/contractor',
  path: '/contractor',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRoute,
} as any)
const OpsIndexRoute = OpsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpsRoute,
} as any)
const DriverIndexRoute = DriverIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DriverRoute,
} as any)
const OwnerSettingsRoute = OwnerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerQueueRoute = OwnerQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerPerformanceRoute = OwnerPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerMoneyRoute = OwnerMoneyRouteImport.update({
  id: '/money',
  path: '/money',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerHistoryRoute = OwnerHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerDriversRoute = OwnerDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerContractorsRoute = OwnerContractorsRouteImport.update({
  id: '/contractors',
  path: '/contractors',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerContractorsIdRoute = OwnerContractorsIdRouteImport.update({
  id: '/owner/contractors/$id',
  path: '/$id',
  getParentRoute: () => OwnerContractorsRoute,
} as any)
const OwnerAiDispatcherRoute = OwnerAiDispatcherRouteImport.update({
  id: '/ai-dispatcher',
  path: '/ai-dispatcher',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerActiveRoute = OwnerActiveRouteImport.update({
  id: '/active',
  path: '/active',
  getParentRoute: () => OwnerRoute,
} as any)
const OpsHistoryRoute = OpsHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => OpsRoute,
} as any)
const OpsContractorsRoute = OpsContractorsRouteImport.update({
  id: '/contractors',
  path: '/contractors',
  getParentRoute: () => OpsRoute,
} as any)
const OpsActiveRoute = OpsActiveRouteImport.update({
  id: '/active',
  path: '/active',
  getParentRoute: () => OpsRoute,
} as any)
const DriverProfileRoute = DriverProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DriverRoute,
} as any)
const DriverOffersRoute = DriverOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => DriverRoute,
} as any)
const DriverHelpRoute = DriverHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => DriverRoute,
} as any)
const DriverEarningsRoute = DriverEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => DriverRoute,
} as any)
const DriverActiveRoute = DriverActiveRouteImport.update({
  id: '/active',
  path: '/active',
  getParentRoute: () => DriverRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/contractor': typeof ContractorRoute
  '/dispatch': typeof DispatchRoute
  '/driver': typeof DriverRouteWithChildren
  '/login': typeof LoginRoute
  '/ops': typeof OpsRouteWithChildren
  '/owner': typeof OwnerRouteWithChildren
  '/driver/active': typeof DriverActiveRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/driver/help': typeof DriverHelpRoute
  '/driver/offers': typeof DriverOffersRoute
  '/driver/profile': typeof DriverProfileRoute
  '/ops/active': typeof OpsActiveRoute
  '/ops/contractors': typeof OpsContractorsRoute
  '/ops/history': typeof OpsHistoryRoute
  '/owner/active': typeof OwnerActiveRoute
  '/owner/ai-dispatcher': typeof OwnerAiDispatcherRoute
  '/owner/contractors': typeof OwnerContractorsRoute
  '/owner/contractors/$id': typeof OwnerContractorsIdRoute
  '/owner/drivers': typeof OwnerDriversRoute
  '/owner/history': typeof OwnerHistoryRoute
  '/owner/money': typeof OwnerMoneyRoute
  '/owner/performance': typeof OwnerPerformanceRoute
  '/owner/queue': typeof OwnerQueueRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/driver/': typeof DriverIndexRoute
  '/ops/': typeof OpsIndexRoute
  '/owner/': typeof OwnerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/contractor': typeof ContractorRoute
  '/dispatch': typeof DispatchRoute
  '/login': typeof LoginRoute
  '/driver/active': typeof DriverActiveRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/driver/help': typeof DriverHelpRoute
  '/driver/offers': typeof DriverOffersRoute
  '/driver/profile': typeof DriverProfileRoute
  '/ops/active': typeof OpsActiveRoute
  '/ops/contractors': typeof OpsContractorsRoute
  '/ops/history': typeof OpsHistoryRoute
  '/owner/active': typeof OwnerActiveRoute
  '/owner/ai-dispatcher': typeof OwnerAiDispatcherRoute
  '/owner/contractors': typeof OwnerContractorsRoute
  '/owner/contractors/$id': typeof OwnerContractorsIdRoute
  '/owner/drivers': typeof OwnerDriversRoute
  '/owner/history': typeof OwnerHistoryRoute
  '/owner/money': typeof OwnerMoneyRoute
  '/owner/performance': typeof OwnerPerformanceRoute
  '/owner/queue': typeof OwnerQueueRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/driver': typeof DriverIndexRoute
  '/ops': typeof OpsIndexRoute
  '/owner': typeof OwnerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/contractor': typeof ContractorRoute
  '/dispatch': typeof DispatchRoute
  '/driver': typeof DriverRouteWithChildren
  '/login': typeof LoginRoute
  '/ops': typeof OpsRouteWithChildren
  '/owner': typeof OwnerRouteWithChildren
  '/driver/active': typeof DriverActiveRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/driver/help': typeof DriverHelpRoute
  '/driver/offers': typeof DriverOffersRoute
  '/driver/profile': typeof DriverProfileRoute
  '/ops/active': typeof OpsActiveRoute
  '/ops/contractors': typeof OpsContractorsRoute
  '/ops/history': typeof OpsHistoryRoute
  '/owner/active': typeof OwnerActiveRoute
  '/owner/ai-dispatcher': typeof OwnerAiDispatcherRoute
  '/owner/contractors': typeof OwnerContractorsRoute
  '/owner/contractors/$id': typeof OwnerContractorsIdRoute
  '/owner/drivers': typeof OwnerDriversRoute
  '/owner/history': typeof OwnerHistoryRoute
  '/owner/money': typeof OwnerMoneyRoute
  '/owner/performance': typeof OwnerPerformanceRoute
  '/owner/queue': typeof OwnerQueueRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/driver/': typeof DriverIndexRoute
  '/ops/': typeof OpsIndexRoute
  '/owner/': typeof OwnerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/403'
    | '/contractor'
    | '/dispatch'
    | '/driver'
    | '/login'
    | '/ops'
    | '/owner'
    | '/driver/active'
    | '/driver/earnings'
    | '/driver/help'
    | '/driver/offers'
    | '/driver/profile'
    | '/ops/active'
    | '/ops/contractors'
    | '/ops/history'
    | '/owner/active'
    | '/owner/ai-dispatcher'
    | '/owner/contractors'
    | '/owner/contractors/$id'
    | '/owner/drivers'
    | '/owner/history'
    | '/owner/money'
    | '/owner/performance'
    | '/owner/queue'
    | '/owner/settings'
    | '/driver/'
    | '/ops/'
    | '/owner/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | '/contractor'
    | '/dispatch'
    | '/login'
    | '/driver/active'
    | '/driver/earnings'
    | '/driver/help'
    | '/driver/offers'
    | '/driver/profile'
    | '/ops/active'
    | '/ops/contractors'
    | '/ops/history'
    | '/owner/active'
    | '/owner/ai-dispatcher'
    | '/owner/contractors'
    | '/owner/contractors/$id'
    | '/owner/drivers'
    | '/owner/history'
    | '/owner/money'
    | '/owner/performance'
    | '/owner/queue'
    | '/owner/settings'
    | '/driver'
    | '/ops'
    | '/owner'
  id:
    | '__root__'
    | '/'
    | '/403'
    | '/contractor'
    | '/dispatch'
    | '/driver'
    | '/login'
    | '/ops'
    | '/owner'
    | '/driver/active'
    | '/driver/earnings'
    | '/driver/help'
    | '/driver/offers'
    | '/driver/profile'
    | '/ops/active'
    | '/ops/contractors'
    | '/ops/history'
    | '/owner/active'
    | '/owner/ai-dispatcher'
    | '/owner/contractors'
    | '/owner/contractors/$id'
    | '/owner/drivers'
    | '/owner/history'
    | '/owner/money'
    | '/owner/performance'
    | '/owner/queue'
    | '/owner/settings'
    | '/driver/'
    | '/ops/'
    | '/owner/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R403Route: typeof R403Route
  ContractorRoute: typeof ContractorRoute
  DispatchRoute: typeof DispatchRoute
  DriverRoute: typeof DriverRouteWithChildren
  LoginRoute: typeof LoginRoute
  OpsRoute: typeof OpsRouteWithChildren
  OwnerRoute: typeof OwnerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractor': {
      id: '/contractor'
      path: '/contractor'
      fullPath: '/contractor'
      preLoaderRoute: typeof ContractorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/': {
      id: '/owner/'
      path: '/'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/ops/': {
      id: '/ops/'
      path: '/'
      fullPath: '/ops/'
      preLoaderRoute: typeof OpsIndexRouteImport
      parentRoute: typeof OpsRoute
    }
    '/driver/': {
      id: '/driver/'
      path: '/'
      fullPath: '/driver/'
      preLoaderRoute: typeof DriverIndexRouteImport
      parentRoute: typeof DriverRoute
    }
    '/owner/settings': {
      id: '/owner/settings'
      path: '/settings'
      fullPath: '/owner/settings'
      preLoaderRoute: typeof OwnerSettingsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/queue': {
      id: '/owner/queue'
      path: '/queue'
      fullPath: '/owner/queue'
      preLoaderRoute: typeof OwnerQueueRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/performance': {
      id: '/owner/performance'
      path: '/performance'
      fullPath: '/owner/performance'
      preLoaderRoute: typeof OwnerPerformanceRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/money': {
      id: '/owner/money'
      path: '/money'
      fullPath: '/owner/money'
      preLoaderRoute: typeof OwnerMoneyRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/history': {
      id: '/owner/history'
      path: '/history'
      fullPath: '/owner/history'
      preLoaderRoute: typeof OwnerHistoryRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/drivers': {
      id: '/owner/drivers'
      path: '/drivers'
      fullPath: '/owner/drivers'
      preLoaderRoute: typeof OwnerDriversRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/contractors': {
      id: '/owner/contractors'
      path: '/contractors'
      fullPath: '/owner/contractors'
      preLoaderRoute: typeof OwnerContractorsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/contractors/$id': {
      id: '/owner/contractors/$id'
      path: '/$id'
      fullPath: '/owner/contractors/$id'
      preLoaderRoute: typeof OwnerContractorsIdRouteImport
      parentRoute: typeof OwnerContractorsRoute
    }
    '/owner/ai-dispatcher': {
      id: '/owner/ai-dispatcher'
      path: '/ai-dispatcher'
      fullPath: '/owner/ai-dispatcher'
      preLoaderRoute: typeof OwnerAiDispatcherRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/active': {
      id: '/owner/active'
      path: '/active'
      fullPath: '/owner/active'
      preLoaderRoute: typeof OwnerActiveRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/ops/history': {
      id: '/ops/history'
      path: '/history'
      fullPath: '/ops/history'
      preLoaderRoute: typeof OpsHistoryRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/contractors': {
      id: '/ops/contractors'
      path: '/contractors'
      fullPath: '/ops/contractors'
      preLoaderRoute: typeof OpsContractorsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/active': {
      id: '/ops/active'
      path: '/active'
      fullPath: '/ops/active'
      preLoaderRoute: typeof OpsActiveRouteImport
      parentRoute: typeof OpsRoute
    }
    '/driver/profile': {
      id: '/driver/profile'
      path: '/profile'
      fullPath: '/driver/profile'
      preLoaderRoute: typeof DriverProfileRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/offers': {
      id: '/driver/offers'
      path: '/offers'
      fullPath: '/driver/offers'
      preLoaderRoute: typeof DriverOffersRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/help': {
      id: '/driver/help'
      path: '/help'
      fullPath: '/driver/help'
      preLoaderRoute: typeof DriverHelpRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/earnings': {
      id: '/driver/earnings'
      path: '/earnings'
      fullPath: '/driver/earnings'
      preLoaderRoute: typeof DriverEarningsRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/active': {
      id: '/driver/active'
      path: '/active'
      fullPath: '/driver/active'
      preLoaderRoute: typeof DriverActiveRouteImport
      parentRoute: typeof DriverRoute
    }
  }
}

interface DriverRouteChildren {
  DriverActiveRoute: typeof DriverActiveRoute
  DriverEarningsRoute: typeof DriverEarningsRoute
  DriverHelpRoute: typeof DriverHelpRoute
  DriverOffersRoute: typeof DriverOffersRoute
  DriverProfileRoute: typeof DriverProfileRoute
  DriverIndexRoute: typeof DriverIndexRoute
}

const DriverRouteChildren: DriverRouteChildren = {
  DriverActiveRoute: DriverActiveRoute,
  DriverEarningsRoute: DriverEarningsRoute,
  DriverHelpRoute: DriverHelpRoute,
  DriverOffersRoute: DriverOffersRoute,
  DriverProfileRoute: DriverProfileRoute,
  DriverIndexRoute: DriverIndexRoute,
}

const DriverRouteWithChildren =
  DriverRoute._addFileChildren(DriverRouteChildren)

interface OpsRouteChildren {
  OpsActiveRoute: typeof OpsActiveRoute
  OpsContractorsRoute: typeof OpsContractorsRoute
  OpsHistoryRoute: typeof OpsHistoryRoute
  OpsIndexRoute: typeof OpsIndexRoute
}

const OpsRouteChildren: OpsRouteChildren = {
  OpsActiveRoute: OpsActiveRoute,
  OpsContractorsRoute: OpsContractorsRoute,
  OpsHistoryRoute: OpsHistoryRoute,
  OpsIndexRoute: OpsIndexRoute,
}

const OpsRouteWithChildren = OpsRoute._addFileChildren(OpsRouteChildren)

interface OwnerRouteChildren {
  OwnerActiveRoute: typeof OwnerActiveRoute
  OwnerAiDispatcherRoute: typeof OwnerAiDispatcherRoute
  OwnerContractorsIdRoute: typeof OwnerContractorsIdRoute
  OwnerContractorsRoute: typeof OwnerContractorsRoute
  OwnerDriversRoute: typeof OwnerDriversRoute
  OwnerHistoryRoute: typeof OwnerHistoryRoute
  OwnerMoneyRoute: typeof OwnerMoneyRoute
  OwnerPerformanceRoute: typeof OwnerPerformanceRoute
  OwnerQueueRoute: typeof OwnerQueueRoute
  OwnerSettingsRoute: typeof OwnerSettingsRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerActiveRoute: OwnerActiveRoute,
  OwnerAiDispatcherRoute: OwnerAiDispatcherRoute,
  OwnerContractorsIdRoute: OwnerContractorsIdRoute,
  OwnerContractorsRoute: OwnerContractorsRoute,
  OwnerDriversRoute: OwnerDriversRoute,
  OwnerHistoryRoute: OwnerHistoryRoute,
  OwnerMoneyRoute: OwnerMoneyRoute,
  OwnerPerformanceRoute: OwnerPerformanceRoute,
  OwnerQueueRoute: OwnerQueueRoute,
  OwnerSettingsRoute: OwnerSettingsRoute,
  OwnerIndexRoute: OwnerIndexRoute,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R403Route: R403Route,
  ContractorRoute: ContractorRoute,
  DispatchRoute: DispatchRoute,
  DriverRoute: DriverRouteWithChildren,
  LoginRoute: LoginRoute,
  OpsRoute: OpsRouteWithChildren,
  OwnerRoute: OwnerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
